### ISSUE TITLE
[beta]Mongo connection fails in new react version of staging

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#10058]
#### Issue Description

I'm trying to confirm a fix for #10027 so I have pulled down the new version of staging.

First issue I had was an eslint dependency issue during `npm install`, I cleared this by clearing my `node_modules` folder and running `npm install` again.

Next, I ran gulp, but all that was in `/map` was 'No Superblocks' so I ran `npm run only-once to re-seed the database.
I then started to get Mongo Errors (pasted below) about not being able to connect.

 I can't clear the mongo issue, I get a nodemon crash and a Mongo error saying "Failed to connect to server".  I've done a `killall -15 mongod` because it was the only way I could stop mongo.  

I then did `mongod --port 27017 --dbpath ./data` I even went as far as `--bind_ip 127.0.0.1` in one instance but I'm still getting the same error

I also tried deleting the `dbpath` and seeding again

```sh
Browse your REST API at http://127.0.0.1:3000/explorer
FreeCodeCamp server listening on port 3000 in development
https redirect listening on port 1337
Connection fails:  { MongoError: failed to connect to server [localhost:27017] on first connect
    at .<anonymous> (/home/stuart/freecodecamp/node_modules/mongodb-core/lib/topologies/server.js:308:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/home/stuart/freecodecamp/node_modules/mongodb-core/lib/connection/pool.js:254:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/home/stuart/freecodecamp/node_modules/mongodb-core/lib/connection/connection.js:160:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:333:8)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect' } 
It will be retried for the next request.
```

#### Browser Information

* Browser Name, Version: Chrome (latest stable)
* Operating System: Ubuntu 16.04 LTS
* Mobile, Desktop, or Tablet: Desktop
* Node v6.3.0
* npm v3.10.3
```sh
mongod --version
'db version v3.2.8
git version: ed70e33130c977bda0024c125b56d159573dbaf0
```

**Comment by BKinahan** [comment]
Just updated my `staging` to see if it's caused by some change there (without clearing/reinstalling modules or the other steps above), but didn't have any problems running `gulp` / connecting to the DB / viewing the map with all challenges.

Haven't tried from a fresh start, though, so I won't say 'could not reproduce.'

**Comment by raisedadead** [comment]
> `mongod --port 1270 --dbpath ./data`

Your db should be running on port `27017` not `1270`

```
refer:
MongoError: failed to connect to server [localhost:27017]
```

**Comment by Bouncey** [comment]
@raisedadead that was a typo in the issue report, I have just confirmed this by running `mongod --port 27017 --dbpath ./data` and still getting the same MongoError

**Comment by Bouncey** [comment]
Output from that command
```sh
2016-08-03T15:31:30.387+0100 I CONTROL  [initandlisten] MongoDB starting : pid=17632 port=27017 dbpath=./data 64-bit host=stuart-PC
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten] db version v3.2.8
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten] git version: ed70e33130c977bda0024c125b56d159573dbaf0
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g-fips  1 Mar 2016
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten] allocator: tcmalloc
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten] modules: none
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten] build environment:
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten]     distmod: ubuntu1404
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten]     distarch: x86_64
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten]     target_arch: x86_64
2016-08-03T15:31:30.388+0100 I CONTROL  [initandlisten] options: { net: { port: 27017 }, storage: { dbPath: "./data" } }
2016-08-03T15:31:30.489+0100 I -        [initandlisten] Detected data files in ./data created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2016-08-03T15:31:30.489+0100 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2016-08-03T15:31:32.550+0100 I CONTROL  [initandlisten] 
2016-08-03T15:31:32.551+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2016-08-03T15:31:32.551+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-08-03T15:31:32.551+0100 I CONTROL  [initandlisten] 
2016-08-03T15:31:32.551+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2016-08-03T15:31:32.551+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-08-03T15:31:32.551+0100 I CONTROL  [initandlisten] 
2016-08-03T15:31:32.630+0100 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory './data/diagnostic.data'
2016-08-03T15:31:32.630+0100 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
2016-08-03T15:31:32.707+0100 I NETWORK  [initandlisten] waiting for connections on port 27017
```

**Comment by BKinahan** [comment]
That looks like standard output for starting up the database, aside from the warnings (which shouldn't affect connections to the database).

**Comment by Bouncey** [comment]
@BKinahan It was more just to show I am using the correct port

**Comment by Bouncey** [comment]
Running mongod as `sudo` (suggested in so) does not change the error

**Comment by dhcodes** [comment]
Maybe worth uninstalling and reinstalling @Bouncey ? http://stackoverflow.com/questions/24547016/uninstall-mongodb-on-mac-os-x

**Comment by BerkeleyTrue** [comment]
React version does not change how FCC connects to mongodb. Can others verify?

**Comment by swimorsink** [comment]
What was the solution you found for this? I'm having a similar problem where my node app connects to the database but then the pool connection fails with the same error you were seeing:

MongoError: failed to connect to server [localhost:27017] on first connect

**Comment by raisedadead** [comment]
@swimorsink 
We did not find a workaround. The error is not reproducible, at least that's the case for most of us.

**Comment by raisedadead** [comment]
@swimorsink This appears to be a loopback issue
https://github.com/strongloop/loopback-connector-mongodb/issues/268
