### ISSUE TITLE
BETA: Loopback blows out on nonprofit links

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/freecodecamp#1022]
http://www.freecodecamp.org/nonprofits/directory

Results in this:
Loopback
500 MongoError: Can't canonicalize query: BadValue unknown operator: $gt
   at Function.MongoError.create (/home/freecodecamp/freecodecamp/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
   at queryCallback (/home/freecodecamp/freecodecamp/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:170:34)
   at Callbacks.emit (/home/freecodecamp/freecodecamp/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:94:3)
   at null.messageHandler (/home/freecodecamp/freecodecamp/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:235:23)
   at Socket.<anonymous> (/home/freecodecamp/freecodecamp/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:259:22)
   at Socket.emit (events.js:107:17)
   at readableAddChunk (_stream_readable.js:163:16)
   at Socket.Readable.push (_stream_readable.js:126:10)
   at TCP.onread (net.js:538:20)

**Comment by BerkeleyTrue** [comment]
Thanks for reporting!

**Comment by BerkeleyTrue** [comment]
works now!
