### ISSUE TITLE
Unable to build or run locally on ubuntu LTS, ENOENT ms/debug/browser

### ISSUE THREAD

**Issue by kzahel** [FreeCodeCamp/FreeCodeCamp#10446]
#### Issue Description
I'm trying to run FCC locally on my ubuntu server. I tried on both ubuntu 16.04 and ubuntu 14.04 and had the same result.

#### versions
```
npm v2.15.9
nodejs v4.5.0
mongodb v3.2.9
```

tlmadmin@tlmvm-fcc14:~/freecodecamp$ npm run build

> freecodecamp@0.1.0 build /home/tlmadmin/freecodecamp
> NODE_ENV=production gulp build -p

[12:01:32] Using gulpfile ~/freecodecamp/gulpfile.js
[12:01:32] Starting 'less'...
[12:01:32] Starting 'js'...
[12:01:32] Starting 'pack-client'...

bundling production

[12:01:40] Finished 'less' after 8.28 s
[12:01:50] Finished 'js' after 18 s
[12:02:13] gulp-notify: [Compile Error] Error in plugin 'webpack-stream'
Message:
    ./~/debug/~/ms/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/home/tlmadmin/freecodecamp/node_modules/debug/node_modules/ms/debug/browser'
    at Error (native)
 @ ./~/debug/debug.js 14:19-32
[12:02:13] gulp-notify: [Error running notifier] Could not send message: not found: notify-send
[12:02:13] Version: webpack 1.13.2
                         Asset      Size  Chunks             Chunk Names
bundle-42aeeb09176114853ad1.js   13.2 MB       0  [emitted]  bundle
           react-manifest.json  51 bytes          [emitted]

WARNING in ./~/babel-core/lib/transformation/file/options/option-manager.js
Critical dependencies:
170:19-37 the request of a dependency is an expression
284:14-32 the request of a dependency is an expression
 @ ./~/babel-core/lib/transformation/file/options/option-manager.js 170:19-37 284:14-32
ERROR in ./~/debug/~/ms/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/home/tlmadmin/freecodecamp/node_modules/debug/node_modules/ms/debug/browser'
    at Error (native)
 @ ./~/debug/debug.js 14:19-32
[12:02:13] Finished 'pack-client' after 41 s
[12:02:13] Starting 'move-webpack-manifest'...
[12:02:13] Finished 'move-webpack-manifest' after 11 ms
[12:02:13] Starting 'clean-webpack-manifest'...
[12:02:13] Starting 'build-manifest'...
[12:02:13] [clean-webpack-manifest] paths deleted/home/tlmadmin/freecodecamp/public/js/react-manifest.json
[12:02:13] Finished 'clean-webpack-manifest' after 12 ms
[12:02:13] Finished 'build-manifest' after 10 ms
[12:02:13] Starting 'build'...
[12:02:13] Finished 'build' after 14 μs
```

**Comment by erictleung** [comment]
@kzahel have you run the commands in the [Getting Started](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#getting-started) section?

```shell
mongod # Run this in a separate terminal
npm run only-once # In another terminal window, run this to seed the database
gulp # This runs the application
```

**Comment by kzahel** [comment]
@erictleung Thank you for looking at my issue.

yes npm run only-once ran and gave no errors. It seeded the database.

mongod is running
```
ps aux | grep mongo
mongodb    996  2.5  3.4 246176 71364 ?        Ssl  12:41   0:00 /usr/bin/mongod --config /etc/mongod.conf
```
gulp will start the development server, but that will crash too with the same error once you start using the website a little.

```
 [4876] template of 4021 referencing  3.05 kB {0} [not cacheable] [built]

WARNING in ./~/babel-core/lib/transformation/file/options/option-manager.js
Critical dependencies:
170:19-37 the request of a dependency is an expression
284:14-32 the request of a dependency is an expression
 @ ./~/babel-core/lib/transformation/file/options/option-manager.js 170:19-37 284:14-32

ERROR in ./~/debug/~/ms/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/home/tlmadmin/freecodecamp/node_modules/debug/node_modules/ms/debug/browser'
    at Error (native)
 @ ./~/debug/debug.js 14:19-32
events.js:141/
      throw er; // Unhandled 'error' event
      ^

Error: watch public/bower_components/rxjs/ts/core/linq/observable/amb.ts ENOSPC
    at exports._errnoException (util.js:907:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/tlmadmin/freecodecamp/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/tlmadmin/freecodecamp/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/tlmadmin/freecodecamp/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/tlmadmin/freecodecamp/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/tlmadmin/freecodecamp/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by BerkeleyTrue** [comment]
Wipe away your node_modules, install npm v3, re-install node modules.

**Comment by kzahel** [comment]
```
npm -v
3.5.2
nodejs -v
v4.2.6
```

that seems to have made the build work. thanks!

**Comment by dhcodes** [comment]
Many thanks @BerkeleyTrue. This was ruining my day.
