### ISSUE TITLE
Issue while running gulp on this project

### ISSUE THREAD

**Issue by RishuK** [FreeCodeCamp/FreeCodeCamp#12336]
I am deploying this project locally for the first time. 

I have ECMAScript6 enabled for javascript in my webstorm. 

However, I keep seeing the following issue while trying to run the gulp command - 

C:\opensource-projects\FreeCodeCamp\gulpfile.js:219
      reqHeaders: ({ url: { hostname } }) => ({
                   ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (C:\Users\rr\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\rr\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:198:16)
    at module.exports (C:\Users\rr\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:17:3)

**Comment by dhcodes** [comment]
See if this thread helps and let us know if you get it remedied: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11044

**Comment by RishuK** [comment]
That worked, indeed a version issue. Thanks @dhcodes

**Comment by dhcodes** [comment]
Closing as resolved
