### ISSUE TITLE
how to run she in my pc with  ubuntu server , what's wrong with me?

### ISSUE THREAD

**Issue by mihongkun** [freeCodeCamp/freeCodeCamp#14485]
#### Challenge Name

 freeCodeCamp git:(staging) gulp
[09:39:41] Using gulpfile ~/githubworkspace/freeCodeCamp/gulpfile.js
[09:39:41] Starting 'less'...
[09:39:41] Starting 'serve'...
[09:39:41] Starting 'js'...
[09:39:41] [nodemon] 1.11.0
[09:39:41] [nodemon] to restart at any time, enter `rs`
[09:39:41] [nodemon] watching: *.*
[09:39:41] [nodemon] starting `node_modules/.bin/babel-node ./server/server.js`
[09:39:41] Finished 'serve' after 320 ms
[09:39:46] Finished 'less' after 5.2 s
[09:39:47] Finished 'js' after 5.35 s
[09:39:47] Starting 'dev-server'...
  fcc:user:remote setting up user hooks +0ms
[09:39:47] Finished 'dev-server' after 171 ms
[09:39:47] Starting 'watch'...
[09:39:47] Finished 'watch' after 126 ms
[09:39:47] Starting 'default'...
[09:39:47] Finished 'default' after 64 μs
[BS] Proxying: http://localhost:3001
[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:3000
    External: http://192.168.199.192:3000
 ----------------------------------------
          UI: http://localhost:3002
 UI External: http://192.168.199.192:3002
 ----------------------------------------
[BS] Watching files...
  fcc:server:utils:about no google applications credentials environmental variable found
  fcc:server:utils:about 'GOOGLE_APPLICATION_CREDENTIALS'
  fcc:server:utils:about 'activeUser' api will always return 0
  fcc:server:utils:about this can safely be ignored during development +525ms

The user model "User" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
User's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep 
the current session valid.

Learn more in our documentation at
https://loopback.io/doc/en/lb2/AccessToken-invalidation.html

The user model "user" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
user's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep 
the current session valid.

Learn more in our documentation at
https://loopback.io/doc/en/lb2/AccessToken-invalidation.html

Error: Connection strategy not found
    at MongoStore (/Users/m/githubworkspace/freeCodeCamp/node_modules/connect-mongo/src/index.js:105:23)
    at sessionsMiddleware (/Users/m/githubworkspace/freeCodeCamp/server/middlewares/sessions.js:15:12)
    at Function.proto.middlewareFromConfig (/Users/m/githubworkspace/freeCodeCamp/node_modules/loopback/lib/server-app.js:74:25)
    at /Users/m/githubworkspace/freeCodeCamp/node_modules/loopback-boot/lib/executor.js:353:9
    at Array.forEach (native)
    at setupMiddleware (/Users/m/githubworkspace/freeCodeCamp/node_modules/loopback-boot/lib/executor.js:340:14)
    at execute (/Users/m/githubworkspace/freeCodeCamp/node_modules/loopback-boot/lib/executor.js:40:3)
    at bootLoopBackApp (/Users/m/githubworkspace/freeCodeCamp/node_modules/loopback-boot/index.js:154:3)
    at Object.<anonymous> (/Users/m/githubworkspace/freeCodeCamp/server/server.js:42:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/m/githubworkspace/freeCodeCamp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/m/githubworkspace/freeCodeCamp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
[09:39:48] [nodemon] app crashed - waiting for file changes before starting...
webpack built ab9cecb5ee656268939e in 20138ms

WARNING in ./~/babel-core/lib/transformation/file/options/option-manager.js
Critical dependencies:
178:19-37 the request of a dependency is an expression
296:16-34 the request of a dependency is an expression
 @ ./~/babel-core/lib/transformation/file/options/option-manager.js 178:19-37 296:16-34

WARNING in ./~/babel-core/lib/transformation/file/index.js
Critical dependencies:
500:24-39 the request of a dependency is an expression
699:16-34 the request of a dependency is an expression
 @ ./~/babel-core/lib/transformation/file/index.js 500:24-39 699:16-34
webpack: Compiled with warnings.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by n0f3** [comment]
Hi, I had the same problem and I've solved by running this command: 
`cp sample.env .env`
*before* running `npm run only-once`
The error is because it can't find the necessary ENV variables.

**Comment by mihongkun** [comment]
thank you

**Comment by n0f3** [comment]
@erictleung this can be closed

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
