### ISSUE TITLE
Tests for Basic Node and Express doesn't work. [Beta]

### ISSUE THREAD

**Issue by w96k** [freeCodeCamp/freeCodeCamp#15442]
http://beta.freecodecamp.com/en/challenges/basic-node-and-express/meet-the-node-console test doesn't work, https://github.com/freeCodeCamp/boilerplate-express/ doesn't work as well.

Here's the error using glitch and my machine.

```TypeError: Cannot read property 'stack' of undefined
    at Object.setupBackgroundApp (/Users/mihailkirillov/Documents/boilerplate-express/node_modules/fcc-express-bground/index.js:149:31)
    at Object.<anonymous> (/Users/mihailkirillov/Documents/boilerplate-express/server.js:25:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)```

**Comment by w96k** [comment]
This problem with an error on glitch was caused because of package.json had server.js links, I changed those to myApp.js. This hadn't helped with fcc testing.

```"main": "myApp.js",
	"scripts": {
		"start": "node myApp.js"```
