### ISSUE TITLE
Bootstrap CDN URL doesn't wrap in Chrome

### ISSUE THREAD

**Issue by akkatracker** [freeCodeCamp/freeCodeCamp#16731]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/applied-responsive-web-design-projects/get-set-for-our-responsive-web-design-projects

#### Issue Description

This wraps fine in Firefox on my Desktop, however doesn't wrap in Chrome on my Laptop - making the content extremely hard to copy without zooming out. 

#### Browser Information

* Browser Name, Version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop (on a 14 inch Laptop)

#### Screenshot
![clipboard01](https://user-images.githubusercontent.com/2032746/36339892-374dc4ea-1423-11e8-97f0-5eec36b11658.png)

**Comment by arpitjindal97** [comment]
This [file](https://beta.freecodecamp.org/css/main-cb9d117fa4.css) needs editing, just `word-wrap: break-word;` needs to be added at this part 
```
.step-description {
  font-size: 1.5em;
}
```
But i am unable to find this file in any of their repositories.

**Comment by jkao1** [comment]
The file you linked is not actually in the codebase; it is just an asset that was versioned (that was the `-cb9d117fa4` at the end of the file) and thrown into a deployment with minified JavaScript.  (Speaking of minified, shouldn't our `gulpfile` minify our CSS? @raisedadead?)

Usually, the files you get by inspecting source are not exactly like that in the codebase. I recommend using our [contributing guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to run Free Code Camp locally. If you inspect source on that development build, as opposed to the production build, you will be able to see which individual CSS file contains the `.step-description` styling.

**Comment by Bouncey** [comment]
Instead of changing the font size, I would rather have some `<wbr>` elements here the url so it can wrap when needed

**Comment by arpitjindal97** [comment]
So, I ran the source locally. Found out that `gulp` is creating `main.css` but still don't know from where it is getting content. 

`step-description` style doesn't exists in any of the files in `public/css/*.css` before running gulp

**Comment by jkao1** [comment]
The `public/` directory holds the production build. The real styling happens in `step.less`. 
![image](https://user-images.githubusercontent.com/15334952/36341048-3853f552-13b6-11e8-90b5-042c323c0779.png)

That file is located in the `common/app/routes/Challenges/views/step` directory. In the file you will see styling for `.step-description`:
```less
@ns: step;

.@{ns}-description {
  font-size: 1.5em;
}
```

However, I agree with @Bouncey that a custom tag for word-breaking would be optimal in this situation.

**Comment by arpitjindal97** [comment]
When running the source locally, i can't click "Go to my next step". 
There is some problem with `bundle.js`. 

![screenshot_2018-02-17_18-36-03](https://user-images.githubusercontent.com/15676216/36341260-950d62dc-1411-11e8-880f-4998dcfe4d50.png)

I have never been comfortable with nodejs 😑

**Comment by Bouncey** [comment]
@arpitjindal97 you need to point your browser to `localhost:3000`

**Comment by arpitjindal97** [comment]
`localhost:3000` does not open at all. It keeps loading and never open.

Logs:

```
remote-redux-devtools: Socket connection errors are being suppressed. 
This can be disabled by setting suppressConnectErrors to 'false'.
{ SocketProtocolError: Socket hung up
    at SCSocket._onSCClose (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/socketcluster-client/lib/scsocket.js:597:15)
    at SCTransport.<anonymous> (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/socketcluster-client/lib/scsocket.js:285:12)
    at SCTransport.Emitter.emit (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/sc-emitter/node_modules/component-emitter/index.js:131:20)
    at SCTransport.SCEmitter.emit (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/sc-emitter/index.js:40:26)
    at SCTransport._onClose (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/socketcluster-client/lib/sctransport.js:181:30)
    at WebSocket.wsSocket.onclose (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/socketcluster-client/lib/sctransport.js:99:10)
    at WebSocket.onClose (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/socketcluster-client/node_modules/ws/lib/EventTarget.js:105:16)
    at WebSocket.emit (events.js:160:13)
    at WebSocket.emitClose (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/socketcluster-client/node_modules/ws/lib/WebSocket.js:227:10)
    at _receiver.cleanup (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/socketcluster-client/node_modules/ws/lib/WebSocket.js:213:41)
    at Receiver.cleanup (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/socketcluster-client/node_modules/ws/lib/Receiver.js:520:15)
    at WebSocket.finalize (/home/arpit/Desktop/workspace/git/freeCodeCamp/node_modules/socketcluster-client/node_modules/ws/lib/WebSocket.js:213:22)
    at TLSSocket.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  name: 'SocketProtocolError',
  message: 'Socket hung up',
  code: 1006 }
```

**Comment by arpitjindal97** [comment]
Solved this issue, I have a device in my network whose hostname is `localhost` so it was connecting to the device rather than loopback.

Earlier, I manually wrote the IP Address in .env file to make mongo work but forgot about this.
