### ISSUE TITLE
`node seed` fails when bootstrapping a new project

### ISSUE THREAD

**Issue by cyberjar09** [freeCodeCamp/freeCodeCamp#17221]
#### Describe your problem and - if possible - how to reproduce it
when starting with a freshly cloned repo and following the steps in the Contributing guide, the step to seed data into MongoDB fails. 
the command `npm run only-once` throws an error.
`node seed` also has the same error

link: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#set-up-freecodecamp

* Operating System: MacOS 10.13.4
* Node: v8.11.2/v8.9.4 (tried both versions, installed via nvm, still same output)
* MongoDB: v3.6.4
* Gulp: v3.9.1
* npm: v5.8.0

CLI output:
```
$ node seed

Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
  fcc:server db connected +0ms
/Users/rudresh/developement/oss/freeCodeCamp/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

Error: Error: entities not found, db may not be properly seeded
    at AnonymousObserver._onError (/Users/rudresh/developement/oss/freeCodeCamp/server/boot/home.js:18:21)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1836:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at AnonymousObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at AnonymousObserver.tryCatcher (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:4530:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at InnerObserver.tryCatcher (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at AutoDetachObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at AutoDetachObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at /Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1904:72
```

**Comment by cyberjar09** [comment]
as requested, tagging @raisedadead

**Comment by raisedadead** [comment]
Can you add additional information on how you have installed `node`? 

`Homebrew` or `nvm` etc.

**Comment by cyberjar09** [comment]
done, added the info into the original issue. (was installed via nvm)

**Comment by Dereje1** [comment]
I'm getting the same error when seeding the database, 

- Operating System: Windows 10 Pro , Version 1803
- Node: 8.9.4
- MongoDB: 3.4.9
- NPM: 6.0.1

**Comment by raisedadead** [comment]
@Dereje1 npm 6 is not working for us. You would have to use npm 5.8.x

**Comment by Dereje1** [comment]
thanks @raisedadead , I was just able to run the learn repo locally no problem with 8.11.2 and 6.0.1, so now I am wondering if I should just stick with that since , if I understood correctly, that is the direction fCC will be going anyway and may be better off learning how to contribute on the learn repo.

**Comment by cyberjar09** [comment]
@Dereje1 which version of MongoDB are you using?

**Comment by nikrb** [comment]
same issue here.
Installed node with nvm install --lts, mongo 3.4.10, ubuntu xenial.
and yarn for learn yes.

**Comment by raisedadead** [comment]
Okay, I don't know if this should matter. But I am on Mongo DB 3.6.x which I believe is the LTS.

```
~/DEV/freeCodeCamp staging
❯ mongod --version
db version v3.6.4
git version: d0181a711f7e7f39e60b5aeb1dc7097bf6ae5856
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

**Comment by Bouncey** [comment]
`node seed/index.js` should keep you going for now. I am about to push a  couple of fixes to the seed so I will take a look.

**Comment by cyberjar09** [comment]
@raisedadead I still have an error when seeding the DB.
```
$ cat /Users/rudresh/.npm/_logs/2018-05-25T00_46_32_498Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/rudresh/.nvm/versions/node/v8.11.2/bin/node',
1 verbose cli   '/Users/rudresh/.nvm/versions/node/v8.11.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'only-once' ]
2 info using npm@5.8.0
3 info using node@v8.11.2
4 verbose run-script [ 'preonly-once', 'only-once', 'postonly-once' ]
5 info lifecycle freecodecamp@0.1.0~preonly-once: freecodecamp@0.1.0
6 info lifecycle freecodecamp@0.1.0~only-once: freecodecamp@0.1.0
7 verbose lifecycle freecodecamp@0.1.0~only-once: unsafe-perm in lifecycle true
8 verbose lifecycle freecodecamp@0.1.0~only-once: PATH: /Users/rudresh/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/rudresh/developement/oss/freeCodeCamp/node_modules/.bin:/Users/rudresh/.nvm/versions/node/v8.11.2/bin:/Users/rudresh/.yarn/bin:/Users/rudresh/.config/yarn/global/node_modules/.bin:/Users/rudresh/.jenv/shims:/Users/rudresh/.jenv/bin:/usr/local/sbin:/usr/local/share/android-sdk/platform-tools:/usr/local/share/android-sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle freecodecamp@0.1.0~only-once: CWD: /Users/rudresh/developement/oss/freeCodeCamp
10 silly lifecycle freecodecamp@0.1.0~only-once: Args: [ '-c',
10 silly lifecycle   'npm run prelint-js && echo \'/****/\' && echo \'Seeding Database\' && echo \'/****/\' && node seed && echo \'/****/\' && echo \'Seeding Completed\' && echo \'/****/\'' ]
11 silly lifecycle freecodecamp@0.1.0~only-once: Returned: code: 1  signal: null
12 info lifecycle freecodecamp@0.1.0~only-once: Failed to exec only-once script
13 verbose stack Error: freecodecamp@0.1.0 only-once: `npm run prelint-js && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/rudresh/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/rudresh/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid freecodecamp@0.1.0
15 verbose cwd /Users/rudresh/developement/oss/freeCodeCamp
16 verbose Darwin 17.5.0
17 verbose argv "/Users/rudresh/.nvm/versions/node/v8.11.2/bin/node" "/Users/rudresh/.nvm/versions/node/v8.11.2/bin/npm" "run" "only-once"
18 verbose node v8.11.2
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error freecodecamp@0.1.0 only-once: `npm run prelint-js && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/'`
22 error Exit status 1
23 error Failed at the freecodecamp@0.1.0 only-once script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by raisedadead** [comment]
Yes @cyberjar09 you are right.

**Comment by raisedadead** [comment]
@cyberjar09 @nikrb @Dereje1 PR is up, you may want to run that manually while the PR gets merged.

After the `npm run only-once fails` simply `run npm run seed`

**Comment by cyberjar09** [comment]
tried the PR, still not working. My steps: 
```
git fetch upstream pull/17232/head:chore/fix-node-seed
git checkout chore/fix-node-seed
npm run only-once # error
node seed # error
```

```
/Users/rudresh/developement/oss/freeCodeCamp/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

Error: Error: entities not found, db may not be properly seeded
    at AnonymousObserver._onError (/Users/rudresh/developement/oss/freeCodeCamp/server/boot/home.js:18:21)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1836:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at AnonymousObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at AnonymousObserver.tryCatcher (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:4530:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at InnerObserver.tryCatcher (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at AutoDetachObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at AutoDetachObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at /Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1904:72
```

@raisedadead

**Comment by cyberjar09** [comment]
after cleaning node_modules and reinstalling
still getting this error 
```
$ npm run only-once

> freecodecamp@0.1.0 only-once /Users/rudresh/developement/oss/freeCodeCamp
> npm run prelint-js && npm run seed && echo 'Seeding Completed'


> freecodecamp@0.1.0 prelint-js /Users/rudresh/developement/oss/freeCodeCamp
> npm run create-rev && gulp generate-migration-map


> freecodecamp@0.1.0 create-rev /Users/rudresh/developement/oss/freeCodeCamp
> node -e "var fs = require('fs'); fs.access('./server/rev-manifest.json', function(err) { if (err) { console.log('\n\ncreating manifest\n\n'); return fs.writeFileSync('server/rev-manifest.json', '{}'); } console.log('\n\nrev-manifest present\n\n'); });"



creating manifest


[10:14:53] Using gulpfile ~/developement/oss/freeCodeCamp/gulpfile.js
[10:14:53] Starting 'generate-migration-map'...
[10:14:54] Finished 'generate-migration-map' after 760 ms

> freecodecamp@0.1.0 seed /Users/rudresh/developement/oss/freeCodeCamp
> node seed/index.js

Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
  fcc:server db connected +0ms
  fcc:seed parsed Applied Accessibility successfully +0ms
  fcc:seed parsed Applied Visual Design successfully +6ms
  fcc:seed parsed Basic CSS successfully +2ms
  fcc:seed parsed Basic HTML and HTML5 successfully +1ms
  fcc:seed parsed CSS Flexbox successfully +2ms
  fcc:seed parsed CSS Grid successfully +1ms
  fcc:seed parsed Responsive Web Design Projects successfully +2ms
  fcc:seed parsed Responsive Web Design Principles successfully +1ms
  fcc:seed parsed Basic Algorithm Scripting successfully +1ms
  fcc:seed parsed Basic Data Structures successfully +2ms
  fcc:seed parsed Basic JavaScript successfully +1ms
  fcc:seed parsed Debugging successfully +2ms
  fcc:seed parsed ES6 successfully +4ms
  fcc:seed parsed Functional Programming successfully +2ms
  fcc:seed parsed Intermediate Algorithm Scripting successfully +1ms
  fcc:seed parsed JavaScript Algorithms and Data Structures Projects successfully +2ms
  fcc:seed parsed Object Oriented Programming successfully +2ms
  fcc:seed parsed Regular Expressions successfully +2ms
  fcc:seed parsed Bootstrap successfully +1ms
  fcc:seed parsed Front End Libraries Projects successfully +1ms
  fcc:seed parsed jQuery successfully +2ms
  fcc:seed parsed React and Redux successfully +1ms
  fcc:seed parsed React successfully +2ms
  fcc:seed parsed Redux successfully +1ms
  fcc:seed parsed Sass successfully +2ms
  fcc:seed parsed Data Visualization Projects successfully +1ms
  fcc:seed parsed Data Visualization with D3 successfully +2ms
  fcc:seed parsed JSON APIs and AJAX successfully +1ms
  fcc:seed parsed APIs and Microservices Projects successfully +1ms
  fcc:seed parsed Basic Node and Express successfully +1ms
  fcc:seed parsed Managing Packages with npm successfully +1ms
  fcc:seed parsed MongoDB and Mongoose successfully +2ms
  fcc:seed parsed Advanced Node and Express successfully +1ms
  fcc:seed parsed Information Security with HelmetJS successfully +1ms
  fcc:seed parsed Information Security and Quality Assurance Projects successfully +1ms
  fcc:seed parsed Quality Assurance and Testing with Chai successfully +1ms
  fcc:seed parsed Algorithms successfully +2ms
  fcc:seed parsed Data Structures successfully +1ms
  fcc:seed parsed Project Euler successfully +1ms
  fcc:seed parsed Rosetta Code successfully +2ms
  fcc:seed parsed Take Home Projects successfully +1ms
  fcc:seed parsed API's and Microservices Certificate successfully +4ms
  fcc:seed parsed Data Visualization Certificate successfully +2ms
  fcc:seed parsed Front End Libraries Certificate successfully +1ms
  fcc:seed parsed Information, Securtiy and Quality Assurance Certificate successfully +1ms
  fcc:seed parsed JavaScript Algorithms and Data Structures Certificate successfully +1ms
  fcc:seed parsed Legacy Back End Certificate successfully +2ms
  fcc:seed parsed Legacy Data Visualization Certificate successfully +1ms
  fcc:seed parsed Legacy Front End Certificate successfully +2ms
  fcc:seed parsed Responsive Web Design Certificate successfully +1ms
/Users/rudresh/developement/oss/freeCodeCamp/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

Error: Error: entities not found, db may not be properly seeded
    at AnonymousObserver._onError (/Users/rudresh/developement/oss/freeCodeCamp/server/boot/home.js:18:21)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1836:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at AnonymousObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at AnonymousObserver.tryCatcher (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:4530:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at InnerObserver.tryCatcher (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1772:14)
    at AutoDetachObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at AutoDetachObserver.o.onError (/Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1999:22)
    at /Users/rudresh/developement/oss/freeCodeCamp/node_modules/rx/dist/rx.js:1904:72
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freecodecamp@0.1.0 seed: `node seed/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the freecodecamp@0.1.0 seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rudresh/.npm/_logs/2018-05-25T03_15_01_384Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freecodecamp@0.1.0 only-once: `npm run prelint-js && npm run seed && echo 'Seeding Completed'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the freecodecamp@0.1.0 only-once script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rudresh/.npm/_logs/2018-05-25T03_15_01_425Z-debug.log
```

my debug log file: 
```
$ cat /Users/rudresh/.npm/_logs/2018-05-25T03_15_01_425Z-debug.log                                                                                      1 ↵
0 info it worked if it ends with ok
1 verbose cli [ '/Users/rudresh/.nvm/versions/node/v8.11.2/bin/node',
1 verbose cli   '/Users/rudresh/.nvm/versions/node/v8.11.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'only-once' ]
2 info using npm@5.8.0
3 info using node@v8.11.2
4 verbose run-script [ 'preonly-once', 'only-once', 'postonly-once' ]
5 info lifecycle freecodecamp@0.1.0~preonly-once: freecodecamp@0.1.0
6 info lifecycle freecodecamp@0.1.0~only-once: freecodecamp@0.1.0
7 verbose lifecycle freecodecamp@0.1.0~only-once: unsafe-perm in lifecycle true
8 verbose lifecycle freecodecamp@0.1.0~only-once: PATH: /Users/rudresh/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/rudresh/developement/oss/freeCodeCamp/node_modules/.bin:/Users/rudresh/.nvm/versions/node/v8.11.2/bin:/Users/rudresh/.yarn/bin:/Users/rudresh/.config/yarn/global/node_modules/.bin:/Users/rudresh/.jenv/shims:/Users/rudresh/.jenv/bin:/usr/local/sbin:/usr/local/share/android-sdk/platform-tools:/usr/local/share/android-sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle freecodecamp@0.1.0~only-once: CWD: /Users/rudresh/developement/oss/freeCodeCamp
10 silly lifecycle freecodecamp@0.1.0~only-once: Args: [ '-c',
10 silly lifecycle   'npm run prelint-js && npm run seed && echo \'Seeding Completed\'' ]
11 silly lifecycle freecodecamp@0.1.0~only-once: Returned: code: 1  signal: null
12 info lifecycle freecodecamp@0.1.0~only-once: Failed to exec only-once script
13 verbose stack Error: freecodecamp@0.1.0 only-once: `npm run prelint-js && npm run seed && echo 'Seeding Completed'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/rudresh/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/rudresh/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid freecodecamp@0.1.0
15 verbose cwd /Users/rudresh/developement/oss/freeCodeCamp
16 verbose Darwin 17.5.0
17 verbose argv "/Users/rudresh/.nvm/versions/node/v8.11.2/bin/node" "/Users/rudresh/.nvm/versions/node/v8.11.2/bin/npm" "run" "only-once"
18 verbose node v8.11.2
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error freecodecamp@0.1.0 only-once: `npm run prelint-js && npm run seed && echo 'Seeding Completed'`
22 error Exit status 1
23 error Failed at the freecodecamp@0.1.0 only-once script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

commit 238657d356
I had local changes: 
```
diff --git a/package.json b/package.json
index 77f783b4a..00b08af2f 100644
--- a/package.json
+++ b/package.json
@@ -17,7 +17,7 @@
     "lint-utils": "jsonlint-cli server/utils/*.json",
     "lint-js": "eslint --ext=.js,.jsx gulpfile.js server/ common/ config/ client/",
     "lint-json": "npm run lint-server && npm run lint-challenges && npm run lint-resources && npm run lint-utils",
-    "only-once": "npm run prelint-js && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/'",
+    "only-once": "npm run prelint-js && npm run seed && echo 'Seeding Completed'",
     "prelint-js": "npm run create-rev && gulp generate-migration-map",
     "pretest": "npm run create-rev && npm run lint",
     "prestart-production": "gulp build -p",
```

**Comment by raisedadead** [comment]
@Bouncey looks like something may have been missed with the migration.
