### ISSUE TITLE
npm install fails (using Ubuntu 16.04)

### ISSUE THREAD

**Issue by cmoss3** [freeCodeCamp/freeCodeCamp#17502]
#### Describe your problem and - if possible - how to reproduce it
When I tried running `npm install` I was prompted with a git error.
The error goes like this: 

```
Unhandled rejection Error: Command failed: /usr/bin/git checkout e158f6bbd631e00e0194515ae25b9971c58a1121
fatal: reference is not a tree: e158f6bbd631e00e0194515ae25b9971c58a1121

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
```
After getting this error I did some googling and found a few people who suggested that downgrading to npm 4 could maybe resolve the issue. So I did downgrade to npm 4 and `npm install` worked after that. However, I ran into yet another (but I think related) issue down the road.

The issue bubbled back up when I tried running the `npm run only-once` command.
It seems that when the seeding process is executed the following error is thrown:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'loopback-component-passport'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/charles/development/freeCodeCamp/server/component-passport.js:2:1)
    at Module._compile (module.js:652:30)
    at loader (/home/charles/development/freeCodeCamp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/charles/development/freeCodeCamp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/charles/development/freeCodeCamp/server/server.js:19:23)
    at Module._compile (module.js:652:30)
    at loader (/home/charles/development/freeCodeCamp/node_modules/babel-register/lib/node.js:144:5)
```
After the installation had seemingly gone successful with npm 4, I was surprised to see this error. I decided to try installing this package individually to see what was happening. So I executed `npm install loopback-component-passport`. I was not given an error to indicate that the install failed:

```
freecodecamp@0.1.0 /home/charles/development/freeCodeCamp
└── @freecodecamp/loopback-component-passport@1.0.0  (git+https://github.com/freeCodeCamp/loopback-component-passport.git#a15739cf00a56602c3c34b1c61c10def273a4c4d)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-prop-toggle@1.0.2 requires a peer of react@^16.3.0 but none was installed.
npm WARN react-prop-toggle@1.0.2 requires a peer of react-dom@^16.3.0 but none was installed.
```
At this point I decided to try running `node seed` to see what would happen, but I was given the same error as before: module "loopback-component-passport" wasn't found.

After this, I upgraded back to the latest version of npm 5 and tried to install the "loopback-component-passport" module individually again. I was given another git error, just like the one I got when I first ran `npm install` with npm 5. I'm pretty sure the "loopback-component-passport" module was the reason my first `npm install` command failed.

With npm 4, the installation seems to work, but when I try executing the app, the "loopback-component-passport" module is unable to be found. 
With npm 5, the installation for the "loopback-component-passport" module fails with the git error I pasted earlier.

#### Tell us about your browser and operating system

* Operating System: **Ubuntu 16.04**

**Comment by cmoss3** [comment]
I thought maybe I could run install through Docker as a work-around, but that hasn't worked either.
I ran `docker-compose run --rm freecodecamp npm install` and got the same git error:
```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout e158f6bbd631e00e0194515ae25b9971c58a1121
npm ERR! fatal: reference is not a tree: e158f6bbd631e00e0194515ae25b9971c58a1121
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-08T22_32_47_158Z-debug.log
```

**Comment by cmoss3** [comment]
This issue was because I forgot to pull down changes from the official staging branch.

1) `git remote add upstream https://github.com/freeCodeCamp/freeCodeCamp.git`
2) `git pull --rebase upstream staging`

**Comment by cmoss3** [comment]
This issue was because I forgot to pull down changes from the official staging branch.

1) `git remote add upstream https://github.com/freeCodeCamp/freeCodeCamp.git`
2) `git pull --rebase upstream staging`
