### ISSUE TITLE
Seeding database fails--utils.js:132

### ISSUE THREAD

**Issue by valvevan** [freeCodeCamp/freeCodeCamp#17989]
freecodecamp$ sudo docker-compose run --rm freecodecamp npm run only-once
[sudo] password for leon:
Starting freecodecamp_mailhog_1 ... done
Starting freecodecamp_db_1 ... done

> freecodecamp@0.1.0 only-once /app
> npm run prelint-js && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed/index.js && echo '/****/' && echo 'Seeding Completed' && echo '/****/'
> freecodecamp@0.1.0 prelint-js /app
> npm run ensure-env
> freecodecamp@0.1.0 ensure-env /app
> node ./config/ensure-env.js
rev-manifest present
pathMigration present
/****/
Seeding Database
/****/
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
(node:50) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
  fcc:server db connected +0ms
/app/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: Error: entities not found, db may not be properly seeded
    at AnonymousObserver._onError (/app/server/boot/home.js:18:21)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/app/node_modules/rx/dist/rx.js:1836:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/app/node_modules/rx/dist/rx.js:1772:14)
    at AnonymousObserver.o.onError (/app/node_modules/rx/dist/rx.js:1999:22)
    at AnonymousObserver.tryCatcher (/app/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/app/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/app/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.error (/app/node_modules/rx/dist/rx.js:4530:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/app/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.o.onError (/app/node_modules/rx/dist/rx.js:1999:22)
    at InnerObserver.tryCatcher (/app/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/app/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/app/node_modules/rx/dist/rx.js:1772:14)
    at AutoDetachObserver.o.onError (/app/node_modules/rx/dist/rx.js:1999:22)
    at AutoDetachObserver.o.onError (/app/node_modules/rx/dist/rx.js:1999:22)
    at /app/node_modules/rx/dist/rx.js:1904:72
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freecodecamp@0.1.0 only-once: `npm run prelint-js && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed/index.js && echo '/****/' && echo 'Seeding Completed' && echo '/****/'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the freecodecamp@0.1.0 only-once script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-08T01_00_55_966Z-debug.log

* Operating System: ubuntu18 docker

**Comment by Nirajn2311** [comment]
Is mongod running in another terminal and try executing the following code separately

``npm run prelint-js && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed/index.js && echo '/****/' && echo 'Seeding Completed' && echo '/****/' ``

**Comment by valvevan** [comment]
no ,when i use mongo client to connect db.It can connect db in the same terminal. @Nirajn2311 .thanks for the reply.
"npm run develop"  same problem.
/app/node_modules/mongodb/lib/utils.js:132
throw err;
^
Error: Error: entities not found, db may not be properly seeded

**Comment by GursimarSinghChopra** [comment]
First wholly remove nodejs and npm from your system.
Then install latest Node version 10.12.0 and npm 6.4.1
Then try if it doesn't work then delete nodesource.list file in your system and try again above steps

**Comment by raisedadead** [comment]
@GursimarSinghChopra We recommend using lts version of node. Details are available in contributing docs. As of this comment, it was 8.x.x.

We have resolved this specific issue with local setup. Please re-clone and make a fresh installation. A few other issues in the setup are still being worked upon. We will post an update in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) when the local is 100% ready.

Thanks

**Comment by raisedadead** [comment]
Closing as stale. The docker setup is probably outdated but we are working on that.
