### ISSUE TITLE
running `npm run only-once` throws error

### ISSUE THREAD

**Issue by Alvin-Voo** [freeCodeCamp/freeCodeCamp#18013]
#### Describe your problem and - if possible - how to reproduce it
I'm installing FCC for the first time, I encountered the issue when running
```
npm run only-once
or
node seed
```
error:

```
Failed loading boot script: /home/alvinvoo/Github Projects/freeCodeCamp/server/boot/z-a-react.js
TypeError: Cannot read property 'string' of undefined
    at Object.<anonymous> (/home/alvinvoo/Github Projects/freeCodeCamp/node_modules/react-d3/barchart/Bar.js:8:27)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/alvinvoo/Github Projects/freeCodeCamp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/alvinvoo/Github Projects/freeCodeCamp/node_modules/react-d3/barchart/BarContainer.js:4:11)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/alvinvoo/Github Projects/freeCodeCamp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
/home/alvinvoo/Github Projects/freeCodeCamp/node_modules/loopback-boot/lib/executor.js:302
      throw err;
```
#### Add a Link to the page with the problem
There's no a page issue.

#### Tell us about your browser and operating system
This is not a browser issue.

* Browser Name: Chromium
* Browser Version: Version 68.0.3440.75 (Official Build)
* Operating System: Ubuntu 18.04

#### If possible, add a screenshot here
![screenshot from 2018-08-15 11-49-05](https://user-images.githubusercontent.com/28261161/44130679-3cb12be4-a081-11e8-8c90-09e0774f8318.png)

#### Possible cause
I did a bit of digging around and found that the error was caused by an outdated library 'react-d3'. This library is being imported in /common/app/routes/Profile/components/HeatMap.jsx.

As per the error message, in the library file /react-d3/barchart/Bar.js, it is using React.PropTypes, which has already been deprecated since React 15.5.0. Read [here](https://reactjs.org/docs/typechecking-with-proptypes.html). 

And it seems like the react-d3 project is kinda [dead](https://github.com/react-d3/react-d3-core/pull/51).

**Comment by raisedadead** [comment]
We have resolved this specific issue with local setup. Please re-clone and make a fresh installation. A few other issues in the setup are still being worked upon. We will post an update in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) when the local is 100% ready.

Thanks
