### ISSUE TITLE
Glitch New Project Error - Mongodb not starting

### ISSUE THREAD

**Issue by birdwell** [freeCodeCamp/freeCodeCamp#18058]
#### Describe your problem and - if possible - how to reproduce it
Go to the Exercise-Tracker
Open in Glitch
Mongodb doesn't start

I tried opening the console in their website and running the mongod command. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/exercise-tracker

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: macOS High Sierra 10.13.6

#### If possible, add a screenshot here
```
vents.js:160

      throw er; // Unhandled 'error' event

      ^

      MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect                       
 ECONNREFUSED 127.0.0.1:27017]

    at Pool.<anonymous> (/rbd/pnpm-volume/9a24fcff-5441-41bc-a3c85c9ff43c50e7/node_modules/.registry.npmjs.org/mongodb-core/2.1.18/node_modules/mongodb-core/lib/topologies/server.js:336:35)

    at emitOne (events.js:96:13)

    at Pool.emit (events.js:188:7)

    at Connection.<anonymous> (/rbd/pnpm-volume/9a24fcff-5441-41bc-a3c8-5c9ff43c50e7/node_modules/.registry.npmjs.org/mongodb-core/2.1.18/node_modules/mongodb-core/lib/connection/pool.js:280:12)

    at Connection.g (events.js:291:16)

    at emitTwo (events.js:106:13)

    at Connection.emit (events.js:191:7)

    at Socket.<anonymous> (/rbd/pnpm-volume/9a24fcff-5441-41bc-a3c8-5c9ff43c50e7/node_modules/.registry.npmjs.org/mongodb-core/2.1.18/node_modules/mongodb-core/lib/connection/connection.js:189:49)

    at Socket.g (events.js:291:16)

    at emitOne (events.js:96:13)

    at Socket.emit (events.js:188:7)

    at emitErrorNT (net.js:1278:8)

    at _combinedTickCallback (internal/process/next_tick.js:74:11)

    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by birdwell** [comment]
Have to use a Mlab Url
