### ISSUE TITLE
../rev-manifest missing

### ISSUE THREAD

**Issue by stanleyyylau** [freeCodeCamp/freeCodeCamp#18118]
#### Describe your problem and - if possible - how to reproduce it

Trying to contributing but get this error while running FCC locally

Error: Cannot find module '../rev-manifest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/stanley/Documents/git-repos/freeCodeCamp/server/middlewares/jade-helpers.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireNodeOrEsModule (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/loopback-boot/lib/require.js:7:17)
    at /Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/loopback-boot/lib/executor.js:351:19
    at Array.forEach (<anonymous>)

#### Add a Link to the page with the problem

No link

#### Tell us about your browser and operating system

* Browser Name: chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System:  mac os 10.12.6 (16G1036)

#### If possible, add a screenshot here

I try deleting all node_modules and reinstall multiple times, still don't work

**Comment by CodingSolo** [comment]
hi @stanleyyylau 
check if .env file exist . if this is not the case:
`copy sample.env .env`

the command `npm run only-once` create rev-manifest file. If you have already run it, you can create the rev-manifest file with `npm run ensure-env`.

Hope that will be useful !

**Comment by stanleyyylau** [comment]
I'm getting some other error when running ``copy sample.env .env && npm run only-once``

/****/
Seeding Database
/****/
Failed loading boot script: /Users/stanley/Documents/git-repos/freeCodeCamp/server/boot/z-a-react.js
TypeError: Cannot read property 'string' of undefined
    at Object.<anonymous> (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/react-d3/barchart/Bar.js:8:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/react-d3/barchart/BarContainer.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/loopback-boot/lib/executor.js:302
      throw err;
      ^

TypeError: Cannot read property 'string' of undefined
    at Object.<anonymous> (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/react-d3/barchart/Bar.js:8:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/react-d3/barchart/BarContainer.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/stanley/Documents/git-repos/freeCodeCamp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by stanleyyylau** [comment]
I deleted all node_modules and reinstal, seem to get FCC seeded, but still get this 

```
gulp[30945]: ../src/node_contextify.cc:627:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100038c65 node::Abort() [/Users/stanley/.nvm/versions/node/v10.9.0/bin/node]
 2: 0x100037d5f node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/Users/stanley/.nvm/versions/node/v10.9.0/bin/node]
 3: 0x1000606f5 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/stanley/.nvm/versions/node/v10.9.0/bin/node]
 4: 0x10023c58f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/stanley/.nvm/versions/node/v10.9.0/bin/node]
 5: 0x10023b72b v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/stanley/.nvm/versions/node/v10.9.0/bin/node]
 6: 0x10023b147 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/stanley/.nvm/versions/node/v10.9.0/bin/node]
 7: 0x1599e195c01d 
 8: 0x1599e190d145 
 9: 0x1599e198b900 
10: 0x1599e19118b5 
11: 0x1599e19118b5 
```

**Comment by CodingSolo** [comment]
Hi @stanleyyylau 
it's a issue with node 10 and gulp. you will find a solution to this problem in [Native crash in Node 10](https://github.com/gulpjs/gulp/issues/2162#issuecomment-384485683)

**Comment by raisedadead** [comment]
Please use the latest LTS version of node and npm. Thanks
