### ISSUE TITLE
Information Security and Quality Assurance Projects - Metric-Imperial Converter: False Positive When Testing User Stories

### ISSUE THREAD

**Issue by cstst** [freeCodeCamp/freeCodeCamp#18142]
I submitted an incomplete version of the Metric-Imperal Converter project, and all of the user stories tests passed. 

[Information Security and Quality Assurance Projects - Metric-Imperial Converter](https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/metric-imperial-converter/)

* Browser Name: Google Chrome
* Browser Version: 68.0.3440.106 
* Operating System: Windows 7 64bit

**Comment by ezioda004** [comment]
I don't think the tests are enabled for "Information Security and Quality Assurance Projects" and "APIs and Microservices Projects".

**Comment by spencercorwin** [comment]
It looks like you can test some of these projects with this link: https://pricey-hugger.glitch.me/

I wouldn't rely on it though.

**Comment by JulianNF** [comment]
Hey @ezioda004 : I figured out while trying to make heads or tails of the boilerplate code that the tests are enabled for the Metric-Imperial Converter project by defining the .env variable `NODE_ENV=test`.

@spencercorwin I found that the [FCC Back-end Tester](https://pricey-hugger.glitch.me/) that you and others have kindly shared didn't work for me. It fails for each test on my project (even with all the boilerplate tests passing) with a not so useful `error: error` message.

I finished my project ([my code here](https://glitch.com/edit/#!/cliff-gray), [my app here](https://cliff-gray.glitch.me)) today and activated the testing suite to make sure everything was working. As soon as you add the `NODE_ENV=test` variable (or un-comment it if you typed it in earlier), the FCC testing code in the boilerplate will run, providing lots of information in the server console.

When I first "activated" the tests , only 10/21 of the unit and functional tests were passing for me. After working through the error messages from the test suite (see below) with the help of lots of console.logs, I was able to get them all to pass (also, see below).

All of the tests (i.e. user stories, unit tests, functional tests) also work perfectly fine when I conduct them manually (they did even when I was only passing 10/21 tests 😄 ... ).

Here's a copy of the log generated by the test suite for my project close to when I first started using the tests:
```
Listening on port 3000
Running Tests...

  Unit Tests
    Function convertHandler.getNum(input)
      ✓ Whole number input
      ✓ Decimal Input
      ✓ Fractional Input
      1) Fractional Input w/ Decimal
      2) Invalid Input (double fraction)
      ✓ No Numerical Input
    Function convertHandler.getUnit(input)
      ✓ For Each Valid Unit Inputs
      3) Unknown Unit Input
    Function convertHandler.getReturnUnit(initUnit)
      4) For Each Valid Unit Inputs
    Function convertHandler.spellOutUnit(unit)
      ✓ For Each Valid Unit Inputs
    Function convertHandler.convert(num, unit)
      ✓ Gal to L
      ✓ L to Gal
      5) Mi to Km
      6) Km to Mi
      7) Lbs to Kg
      8) Kg to Lbs
 

 Functional Tests
    Routing Tests
      GET /api/convert => conversion object
        ✓ Convert 10L (valid input) (39ms)
        9) Convert 32g (invalid input unit)
        10) Convert 3/7.2/4kg (invalid number)
        11) Convert 3/7.2/4kilomegagram (invalid number and unit)
        ✓ Convert kg (no number)
  
10 passing (153ms)
11 failing

  1) Unit Tests Function convertHandler.getNum(input) Fractional Input w/ Decimal:
     AssertionError: expected 1 to equal 0.25
      at Context.<anonymous> (tests/1_unit-tests.js:65:14)
  2) Unit Tests Function convertHandler.getNum(input) Invalid Input (double fraction):
     AssertionError: expected 1 to equal 'invalid number'
      at Context.<anonymous> (tests/1_unit-tests.js:74:14)
  3) Unit Tests Function convertHandler.getUnit(input) Unknown Unit Input:
     TypeError: input.ofrEach is not a function
      at Context.<anonymous> (tests/1_unit-tests.js:119:13)
  4) Unit Tests Function convertHandler.getReturnUnit(initUnit) For Each Valid Unit Inputs:
     AssertionError: expected 'L' to equal 'l'
      at tests/1_unit-tests.js:140:16
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (tests/1_unit-tests.js:139:13)
  5) Unit Tests Function convertHandler.convert(num, unit) Mi to Km:
     TypeError: convertHandler is not a function
      at Context.<anonymous> (tests/1_unit-tests.js:197:28)
  6) Unit Tests Function convertHandler.convert(num, unit) Km to Mi:
     TypeError: convertHandler is not a function
      at Context.<anonymous> (tests/1_unit-tests.js:206:28)
  7) Unit Tests Function convertHandler.convert(num, unit) Lbs to Kg:
     TypeError: convertHandler is not a function
      at Context.<anonymous> (tests/1_unit-tests.js:215:28)
  8) Unit Tests Function convertHandler.convert(num, unit) Kg to Lbs:
     TypeError: convertHandler is not a function
      at Context.<anonymous> (tests/1_unit-tests.js:224:28)
  9) Functional Tests Routing Tests GET /api/convert => conversion object Convert 32g (invalid input unit):
     Uncaught AssertionError: expected undefined to equal 32
      at tests/2_functional-tests.js:59:20
      at Test.Request.callback (/rbd/pnpm-volume/3521b72b-1e6f-4711-9914-d6df58c8ba57/node_modules/.registry.npmjs.org/superagent/2.3.0/node_modules/superagent/lib/node/index.js:619:12)
      at /rbd/pnpm-volume/3521b72b-1e6f-4711-9914-d6df58c8ba57/node_modules/.registry.npmjs.org/superagent/2.3.0/node_modules/superagent/lib/node/index.js:795:18
      at IncomingMessage.<anonymous> (/rbd/pnpm-volume/3521b72b-1e6f-4711-9914-d6df58c8ba57/node_modules/.registry.npmjs.org/superagent/2.3.0/node_modules/superagent/lib/node/parsers/json.js:16:7)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  10) Functional Tests Routing Tests GET /api/convert => conversion object Convert 3/7.2/4kg (invalid number):
     Uncaught AssertionError: expected undefined to equal 'invalid number'
      at tests/2_functional-tests.js:78:20
      at Test.Request.callback (/rbd/pnpm-volume/3521b72b-1e6f-4711-9914-d6df58c8ba57/node_modules/.registry.npmjs.org/superagent/2.3.0/node_modules/superagent/lib/node/index.js:619:12)
      at /rbd/pnpm-volume/3521b72b-1e6f-4711-9914-d6df58c8ba57/node_modules/.registry.npmjs.org/superagent/2.3.0/node_modules/superagent/lib/node/index.js:795:18
      at IncomingMessage.<anonymous> (/rbd/pnpm-volume/3521b72b-1e6f-4711-9914-d6df58c8ba57/node_modules/.registry.npmjs.org/superagent/2.3.0/node_modules/superagent/lib/node/parsers/json.js:16:7)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  11) Functional Tests Routing Tests GET /api/convert => conversion object Convert 3/7.2/4kilomegagram (invalid number and unit):
     Uncaught AssertionError: expected undefined to equal 'invalid number'
      at tests/2_functional-tests.js:97:20
      at Test.Request.callback (/rbd/pnpm-volume/3521b72b-1e6f-4711-9914-d6df58c8ba57/node_modules/.registry.npmjs.org/superagent/2.3.0/node_modules/superagent/lib/node/index.js:619:12)
      at /rbd/pnpm-volume/3521b72b-1e6f-4711-9914-d6df58c8ba57/node_modules/.registry.npmjs.org/superagent/2.3.0/node_modules/superagent/lib/node/index.js:795:18
      at IncomingMessage.<anonymous> (/rbd/pnpm-volume/3521b72b-1e6f-4711-9914-d6df58c8ba57/node_modules/.registry.npmjs.org/superagent/2.3.0/node_modules/superagent/lib/node/parsers/json.js:16:7)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

... and here is my test log once I had resolved all the errors:
```
Listening on port 3000
Running Tests...

  Unit Tests
    Function convertHandler.getNum(input)
      ✓ Whole number input
      ✓ Decimal Input
      ✓ Fractional Input
      ✓ Fractional Input w/ Decimal
      ✓ Invalid Input (double fraction)
      ✓ No Numerical Input
    Function convertHandler.getUnit(input)
      ✓ For Each Valid Unit Inputs
      ✓ Unknown Unit Input
    Function convertHandler.getReturnUnit(initUnit)
      ✓ For Each Valid Unit Inputs
    Function convertHandler.spellOutUnit(unit)
      ✓ For Each Valid Unit Inputs
    Function convertHandler.convert(num, unit)
      ✓ Gal to L
      ✓ L to Gal
      ✓ Mi to Km
      ✓ Km to Mi
      ✓ Lbs to Kg
      ✓ Kg to Lbs
  

  Functional Tests
    Routing Tests
      GET /api/convert => conversion object
        ✓ Convert 10L (valid input) (150ms)
        ✓ Convert 32g (invalid input unit) (105ms)
        ✓ Convert 3/7.2/4kg (invalid number)
        ✓ Convert 3/7.2/4kilomegagram (invalid number and unit)
        ✓ Convert kg (no number)
  

  21 passing (510ms)
```

Hope this helps someone else out there who has had to muddle their way through the lacking instructions for this project.

**Comment by moT01** [comment]
Tests aren't added to the challenge file for this project. There's another [open issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/37185) to address this and the other projects without tests. I am going to close this since we are tracking things over there. Thanks for all the input everyone.
