### ISSUE TITLE
npm run seed error - Cannot find module './build/curriculum-english.json'

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#18459]
When I execute the command `npm run seed` I get the following error:

```
Nandish@Niraj MINGW64 ~/Desktop/VSCode/Free-Code-Camp/freeCodeCamp (master)
$ npm run seed

> @freecodecamp/freecodecamp@0.0.1 seed C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\freeCodeCamp
> node tools/scripts/seed/seedChallenges

C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\freeCodeCamp\tools\scripts\seed\node_modules\mongodb\lib\utils.js:132
      throw err;
      ^

Error: Cannot find module './build/curriculum-english.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at getCurriculum (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\freeCodeCamp\curriculum\lib.js:19:22)
    at challenges.deleteMany.err (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\freeCodeCamp\tools\scripts\seed\seedChallenges.js:43:26)
    at result (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\freeCodeCamp\tools\scripts\seed\node_modules\mongodb\lib\utils.js:414:17)
    at session.endSession (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\freeCodeCamp\tools\scripts\seed\node_modules\mongodb\lib\utils.js:401:11)
    at ClientSession.endSession (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\freeCodeCamp\tools\scripts\seed\node_modules\mongodb-core\lib\sessions.js:129:41)
    at executeCallback (C:\Users\Nandish\Desktop\VSCode\Free-Code-Camp\freeCodeCamp\tools\scripts\seed\node_modules\mongodb\lib\utils.js:397:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freecodecamp/freecodecamp@0.0.1 seed: `node tools/scripts/seed/seedChallenges`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nandish\AppData\Roaming\npm-cache\_logs\2018-10-12T13_44_58_047Z-debug.log

```

OS Version - WIndows 10 1809
Node version - v8.12.0
NPM version - 6.4.1
MongoDB version - v4.0.2

**Comment by GursimarSinghChopra** [comment]
First wholly remove nodejs and npm from your system.
Then install latest Node version 10.12.0 and npm 6.4.1
Then try if it doesn't work then delete nodesource.list file in your system

**Comment by sidemt** [comment]
I'm getting the same error.
Updating to Node version 10.12.0 did not solve the problem for me. I haven't tried uninstalling nodejs and npm yet though.

OS Version - WIndows 10 Home
Node version - v8.12.0 -> updated to v10.12.0
NPM version - 6.4.1
MongoDB version - v3.6.8

**Comment by raisedadead** [comment]
We have resolved this specific issue with local setup. Please re-clone and make a fresh installation. A few other issues in the setup are still being worked upon. We will post an update in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) when the local is 100% ready.

Thanks

**Comment by 0jordanmiller** [comment]
Hi, I am having this same problem when I run npm run seed. Was there an update? I just joined, so I might have missed it while scrolling up.

Environment:
OS: Linux Mint 18.2 Sonya
Node.js v8 12.0
MongoDB shell version: 2.6.10
