### ISSUE TITLE
Fresh install mongoose error?

### ISSUE THREAD

**Issue by jameskopacz** [FreeCodeCamp/freecodecamp#270]
```
> node seed_data/seed.js


##############################################################
#
#   !!! MONGOOSE WARNING !!!
#
#   This is an UNSTABLE release of Mongoose.
#   Unstable releases are available for preview/testing only.
#   DO NOT run this in production.
#
##############################################################

E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\base.js:246
        throw message;
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1581:31)
    at E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1619:20
    at E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1157:7
    at E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1890:9
    at Server.Base._callHandler (E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\base.js:448:41)
    at E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:481:18
    at MongoReply.parseBody (E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js:68:5)
    at null.<anonymous> (E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:439:20)
    at emit (events.js:107:17)
    at null.<anonymous> (E:\www\public_html\github\freecodecamp\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:201:13)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\Program Files\\nodejs\\\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! freecodecamp@0.1.0 postinstall: `node seed_data/seed.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the freecodecamp@0.1.0 postinstall script 'node seed_data/seed.js'.
npm ERR! This is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node seed_data/seed.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\www\public_html\github\freecodecamp\npm-debug.log
```
Changing ```"mongoose": "^3.8.19",``` to ```"mongoose": "^4.0.0",``` in package.json fixed the error.

**Comment by terakilobyte** [comment]
Yeah the feature branch we're working on that is super close to release already has addressed this. Not sure how or why Mongoose got set to an experimental(and old) version.
