### ISSUE TITLE
Problem with running project locally

### ISSUE THREAD

**Issue by dmytroyarmak** [FreeCodeCamp/FreeCodeCamp#2873]
Hello,
I'm trying to run this project on my machine but I have an error when I'm trying to run the server or make `node seed/`.

I'm using OSX 10.10.5 and I've tryid both 0.11 and 0.12 versions of node.

Here is what I have:
```
➜  FreeCodeCamp git:(staging) node seed/
no original function chain to wrap
TypeError: undefined is not a function
    at getConfigVariable (/Users/d.yarmak/Projects/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:330:32)
    at Array.map (native)
    at /Users/d.yarmak/Projects/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:348:41
    at Array.forEach (native)
    at interpolateVariables (/Users/d.yarmak/Projects/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:345:25)
    at getUpdatedConfigObject (/Users/d.yarmak/Projects/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:360:10)
    at /Users/d.yarmak/Projects/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:319:19
    at Array.forEach (native)
    at setupMiddleware (/Users/d.yarmak/Projects/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:310:14)
    at execute (/Users/d.yarmak/Projects/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:33:3)
    at bootLoopBackApp (/Users/d.yarmak/Projects/FreeCodeCamp/node_modules/loopback-boot/index.js:140:3)
    at Object.<anonymous> (/Users/d.yarmak/Projects/FreeCodeCamp/server/server.js:37:1)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/d.yarmak/Projects/FreeCodeCamp/node_modules/babel-core/lib/babel/api/register/node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/d.yarmak/Projects/FreeCodeCamp/node_modules/babel-core/lib/babel/api/register/node.js:179:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/d.yarmak/Projects/FreeCodeCamp/seed/index.js:7:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.
```

**Comment by BerkeleyTrue** [comment]
This issue has been solved. Please pull down latest, remove previously installed node modules, and run npm install again.

Happy Coding!
