### ISSUE TITLE
Cannot seed database on OS X

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#3333]
I've tried for days to get the FreeCodeCamp repo running on my Mac, and always get the same error message at the `node seed/` step:

```
Error: Cannot find module 'node_modules/loopback'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.<anonymous> (/Users/leon/Developer/GitHub/FreeCodeCamp/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/leon/Developer/GitHub/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:313:19
    at Array.forEach (native)
    at setupMiddleware (/Users/leon/Developer/GitHub/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:310:14)
    at execute (/Users/leon/Developer/GitHub/FreeCodeCamp/node_modules/loopback-boot/lib/executor.js:33:3)
    at bootLoopBackApp (/Users/leon/Developer/GitHub/FreeCodeCamp/node_modules/loopback-boot/index.js:136:3)
```

So far I've tried: node 0.12.7 and 4.0.0; npm 2.11.3, 2.14.2, and 3.3.3; half a dozen different versions of loopback, loopback-component-passport, and loopback-boot (besides FCC's custom versions). It makes no difference whether I have strongloop installed globally or not. And in case you're wondering, I do have mongod running and have run `use freecodecamp` in mongo client.

I'm at my wits' end. Could someone please point me in the right direction? Thanks!

**Comment by bugron** [comment]
@leonfeng Try to run `npm install loopback` one more time,

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by BerkeleyTrue** [comment]
try running this, in order, in the root of the project directory.
```
rm -rf node_modules/
npm install
```

**Comment by leonfeng** [comment]
Thanks for the replies. Tried both your suggestions, but unfortunately got the same result. It's probably to do with my particular setup. 

I even tried setting up the repo on Cloud9. To my distress, `npm install` gets killed for hitting memory limit  every time. I think I'm gonna roll a Linux VM just for contributing to Free Code Camp…
