### ISSUE TITLE
[Staging] Loopback error when accessing challenges

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/FreeCodeCamp#3730]
When running the FCC staging branch as usual via gulp I get the following error when trying to access challenges.
```
500 TypeError: predicate.call is not a function

       at /Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:5130:78
       at tryCatcher (/Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:567:29)
       at InnerObserver.onNext (/Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:5147:49)
       at InnerObserver.tryCatcher (/Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:567:29)
       at AutoDetachObserverPrototype.next (/Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:5274:51)
       at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:1710:35)
       at /Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:1855:51
       at /Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:1884:13
       at scheduleInnerRecursive (/Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:1085:7)
       at recursiveAction (/Users/logan/development/FreeCodeCamp/node_modules/rx/dist/rx.js:1039:9)
```

I can not reproduce the error on any other pages, but every single challenge will cause this.

Last I'd run the staging branch is 2 days ago, so I only know the change is more recent than that.

**Comment by BerkeleyTrue** [comment]
Hey @ltegman, We just merged updates to packages. Please wipe out your node modules and do another npm install

```bash
rm -rf node_modules/
npm install
```

Let me know how that works for you.

**Comment by ltegman** [comment]
Doh -- that did the trick! Thanks :)

**Comment by BerkeleyTrue** [comment]
Awesome!

Happy Coding!
