### ISSUE TITLE
Donate page crashes upon credit card submission

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37403]
Steps to reproduce:
1. Go to https://www.freecodecamp.org/donate
2. Enter your credit card information and hit submit
3. The transaction will not go through (won't show up in Stripe) and you'll get a blank page like this:

<img width="1427" alt="Support_our_nonprofit___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/67155130-b972bd00-f2ce-11e9-97a5-8210f6482982.png">

**Comment by ahmadabdolsaheb** [comment]
reproducible on master
```
{ Error: Access token is required for this request
    at requestAuthorisation (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/server/middlewares/request-authorization.js:37:11)
    at Layer.handle [as handle_request] (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:317:13)
    at /Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/cookie-parser/index.js:57:14)
    at Layer.handle [as handle_request] (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:317:13)
    at /Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:275:10)
    at next (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/server/middlewares/add-return-to.js:30:14)
    at Layer.handle [as handle_request] (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:317:13)
    at /Users/ahmadabdolsaheb/Desktop/fcc/api-server/node_modules/express/lib/router/index.js:284:7
  [Symbol(handledError)]:
   { type: 'info',
     message: 'Access token is required for this request',
     redirectTo: undefined,
     status: 403 } }
```

**Comment by raisedadead** [comment]
I am aware of this issue, working on it.
