### ISSUE TITLE
Error in Waypoint: Get Set for Basejumps

### ISSUE THREAD

**Issue by jayhawk** [FreeCodeCamp/FreeCodeCamp#3810]
Hi I got the following error while answering the following question which is not listed in waypoint.

>What would you like to write tests with? Jasmine
You're using the fantastic NgComponent generator.
Initializing yo-rc.json configuration.

>events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object [object Object] has no method 'isAbsolute'
    at Generator.processDirectory (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:110:19)
    at Generator.generateProject (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/app/generator.js:399:14)
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:354:15)

**Comment by awesomeaniruddh** [comment]
Closing the issue because we have stopped supporting `angular-fullstack`. If you're facing any issues with Clementine, then please open a new issue for that. Thanks!
