### ISSUE TITLE
`build` script not running on Windows

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#39458]
**Describe the bug**

The `npm run build` command errors out on Windows. This is the error message I get when I run it -

```bash
PS D:\xampp\htdocs\gitcontributions\freeCodeCamp> npm run build

> @freecodecamp/freecodecamp@0.0.1 build D:\xampp\htdocs\gitcontributions\freeCodeCamp
> npm-run-all ensure-env -p build:*


> @freecodecamp/freecodecamp@0.0.1 ensure-env D:\xampp\htdocs\gitcontributions\freeCodeCamp
> cross-env DEBUG=fcc:* node ./tools/scripts/build/ensure-env.js

  fcc:tools:ensure-env pathMigration present +0ms

> @freecodecamp/freecodecamp@0.0.1 build:client D:\xampp\htdocs\gitcontributions\freeCodeCamp
> cd ./client && npm run build


> @freecodecamp/freecodecamp@0.0.1 build:server D:\xampp\htdocs\gitcontributions\freeCodeCamp
> cd ./api-server && npm run build


> @freecodecamp/api-server@0.0.1 build D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server
> babel server --out-dir lib --ignore 'node_modules /**/*','/**/*.test.js' --copy-files

& node ../tools/scripts/build/ensure-env.js

'Client workers building...'  workers ready.' &
Error: EPERM: operation not permitted, scandir 'D:/$RECYCLE.BIN/S-1-5-18'
    at Object.readdirSync (fs.js:955:3)
    at GlobSync._readdir (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:288:41)
    at GlobSync._readdirInGlobStar (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:267:20)
    at GlobSync._readdir (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:276:17)
    at GlobSync._processReaddir (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:137:22)
    at GlobSync._process (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:132:10)
    at GlobSync._processGlobStar (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:380:10)
    at GlobSync._process (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:130:10)
    at GlobSync._processGlobStar (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:383:10)
    at GlobSync._process (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:130:10) {
  errno: -4048,
  syscall: 'scandir',
  code: 'EPERM',
  path: 'D:/$RECYCLE.BIN/S-1-5-18'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freecodecamp/api-server@0.0.1 build: `babel server --out-dir lib --ignore 'node_modules /**/*','/**/*.test.js' --copy-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @freecodecamp/api-server@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev\AppData\Roaming\npm-cache\_logs\2020-08-24T07_01_59_666Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freecodecamp/freecodecamp@0.0.1 build:server: `cd ./api-server && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 build:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev\AppData\Roaming\npm-cache\_logs\2020-08-24T07_01_59_694Z-debug.log
ERROR: "build:server" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freecodecamp/freecodecamp@0.0.1 build: `npm-run-all ensure-env -p build:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev\AppData\Roaming\npm-cache\_logs\2020-08-24T07_01_59_839Z-debug.log
```

**To Reproduce**
1. Follow the steps to be able the run the dev server locally
2. Run `npm run build`

**Expected behavior**

The `build` script should run and build the production build which I'll be able to use with the `start` script.

**Desktop (please complete the following information):**
 - OS: Windows 10 (v2004) (64 Bit)
 - Node Version: v12.18.3

**Additional context**

I can currently run the dev server in Windows **after** applying the fixes in #39374 and #39454 manually.

**Comment by SaumitraVerma** [comment]
You should launch PowerShell as administrator.

**Comment by ojeytonwilliams** [comment]
There shouldn't be any need to have elevated privileges when running fCC.  There's no need on 'nix systems, so hopefully Windows is the same.

**Comment by SaumitraVerma** [comment]
So, I think you should try it on command prompt instead of PS.

**Comment by Twaha-Rahman** [comment]
I tried running the `build` script both in `cmd` and `powershell` with and without admin rights and it still fails.

I'll look more into it once I have some time.

**Comment by SaumitraVerma** [comment]
I think there is a problem with permissions only as the first error is
`'Client workers building...'  workers ready.' &
Error: EPERM: operation not permitted, scandir 'D:/$RECYCLE.BIN/S-1-5-18'
    at Object.readdirSync (fs.js:955:3)
    at GlobSync._readdir (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:288:41)
    at GlobSync._readdirInGlobStar (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:267:20)
    at GlobSync._readdir (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:276:17)
    at GlobSync._processReaddir (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:137:22)
    at GlobSync._process (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:132:10)
    at GlobSync._processGlobStar (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:380:10)
    at GlobSync._process (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:130:10)
    at GlobSync._processGlobStar (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:383:10)
    at GlobSync._process (D:\xampp\htdocs\gitcontributions\freeCodeCamp\api-server\node_modules\glob\sync.js:130:10) {
  errno: -4048,
  syscall: 'scandir',
  code: 'EPERM',
  path: 'D:/$RECYCLE.BIN/S-1-5-18'
}`
and it clearly states `operation not permitted` 
You can try this-
- npm cache clean --force
- delete node_modules folder
- delete package-lock.json file
- npm install

**Comment by raisedadead** [comment]
Recommend using WSL on Windows 10 (we do not have support for older OS), or alternatively use GitPod.
