### ISSUE TITLE
Waypoint: Start a Nodejs Server

### ISSUE THREAD

**Issue by kkennethlee** [FreeCodeCamp/FreeCodeCamp#4153]
http://www.freecodecamp.com/challenges/waypoint-start-a-nodejs-server

Hello. I am trying to start this exercise but I cannot seem to proceed. Thank you in advance.

After running the command:         sudo npm install -g learnyounode
and             learnyounode

I try to start "Hello World"

only to run into this:

module.js:338
    throw err;
    ^

Error: Cannot find module 'ansicolors'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyounode/node_modules/workshopper-adventure/node_modules/@leichtgewicht/msee/lib/syntaxColor.js:1:76)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by ltegman** [comment]
Can confirm this is happening in C9 but it doesn't happen when I install locally on an Ubuntu VM. Do we want to leave this open or close in favor of a bug on the learnyounode repo?

**Comment by BerkeleyTrue** [comment]
This should be opened on learnyounode's repo.

**Comment by ltegman** [comment]
Looks like there is already an open bug in the learnyounode repo with a fix ETA of EOD - https://github.com/workshopper/learnyounode/issues/374

Closing this issue.

Thanks and happy coding!
