### ISSUE TITLE
cannot submit JavaScript certification projects

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#43201]
Submitting JavaScript project solution isn't saved. Api request to `/modern-challenge-completed` ends up with error.

```
Original request: POST /modern-challenge-completed
Stack: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at buildUserUpdate (/workspace/freeCodeCamp/api-server/src/server/boot/challenge.js:86:21)
    at /workspace/freeCodeCamp/api-server/src/server/boot/challenge.js:225:48
    at tryCatcher (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:1762:31)
    at loopRecursive (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:2760:13)
    at Rx.internals.ScheduledItem.invokeRecImmediate [as action] (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:967:7)
    at Rx.internals.ScheduledItem.ScheduledItem.invokeCore (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:896:33)
    at Rx.internals.ScheduledItem.ScheduledItem.invoke (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:884:40)
    at runTrampoline (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:1125:37)
    at tryCatcher (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:63:31)
    at CurrentThreadScheduler.schedule (/workspace/freeCodeCamp/api-server/node_modules/rx/dist/rx.js:1141:45)

// raw
{}
```

I've found one way to fix it - to add default value to `files` either in
https://github.com/freeCodeCamp/freeCodeCamp/blob/59f17f237ba2abfdef28a3cf1b4a9dba12de0eee/api-server/src/server/boot/challenge.js#L223
or 
https://github.com/freeCodeCamp/freeCodeCamp/blob/59f17f237ba2abfdef28a3cf1b4a9dba12de0eee/api-server/src/server/boot/challenge.js#L81
i.e.:
```
files = {}
```

## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/palindrome-checker
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/roman-numeral-converter
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/caesars-cipher
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/telephone-number-validator
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register

## Additional context

Thread with report https://forum.freecodecamp.org/t/cant-claim-certificate-for-js-and-ds/473785/4

**Comment by ShaunSHamilton** [comment]
The quick fix has been to roll-back production to before this bug. As such, this bug exists only on the `main` branch.
