### ISSUE TITLE
Something went wrong installing the "sharp" module  Cannot find module '../build/Release/sharp-linux-x64.node' on Ubuntu

### ISSUE THREAD

**Issue by diivi** [freeCodeCamp/freeCodeCamp#43640]
## Affected page

https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=step-4-start-the-freecodecamp-client-application-and-api-server

## To reproduce

`npm run develop`
versions:
node v14.17.10
npm v6.14.13

## log 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'develop' ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'predevelop', 'develop', 'postdevelop' ]
5 info lifecycle @freecodecamp/freecodecamp@0.0.1~predevelop: @freecodecamp/freecodecamp@0.0.1
6 verbose lifecycle @freecodecamp/freecodecamp@0.0.1~predevelop: unsafe-perm in lifecycle true
7 verbose lifecycle @freecodecamp/freecodecamp@0.0.1~predevelop: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/divyansh/Desktop/Projects/Open Source/freeCodeCamp/node_modules/.bin:/opt/firefox/firefox:/home/divyansh/anaconda3/bin:/home/divyansh/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
8 verbose lifecycle @freecodecamp/freecodecamp@0.0.1~predevelop: CWD: /home/divyansh/Desktop/Projects/Open Source/freeCodeCamp
9 silly lifecycle @freecodecamp/freecodecamp@0.0.1~predevelop: Args: [ '-c', 'npm run ensure-env' ]
10 silly lifecycle @freecodecamp/freecodecamp@0.0.1~predevelop: Returned: code: 0  signal: null
11 info lifecycle @freecodecamp/freecodecamp@0.0.1~develop: @freecodecamp/freecodecamp@0.0.1
12 verbose lifecycle @freecodecamp/freecodecamp@0.0.1~develop: unsafe-perm in lifecycle true
13 verbose lifecycle @freecodecamp/freecodecamp@0.0.1~develop: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/divyansh/Desktop/Projects/Open Source/freeCodeCamp/node_modules/.bin:/opt/firefox/firefox:/home/divyansh/anaconda3/bin:/home/divyansh/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
14 verbose lifecycle @freecodecamp/freecodecamp@0.0.1~develop: CWD: /home/divyansh/Desktop/Projects/Open Source/freeCodeCamp
15 silly lifecycle @freecodecamp/freecodecamp@0.0.1~develop: Args: [ '-c', 'npm-run-all build:curriculum -p develop:*' ]
16 silly lifecycle @freecodecamp/freecodecamp@0.0.1~develop: Returned: code: 1  signal: null
17 info lifecycle @freecodecamp/freecodecamp@0.0.1~develop: Failed to exec develop script
18 verbose stack Error: @freecodecamp/freecodecamp@0.0.1 develop: `npm-run-all build:curriculum -p develop:*`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:376:20)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:376:20)
18 verbose stack     at maybeClose (internal/child_process.js:1055:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
19 verbose pkgid @freecodecamp/freecodecamp@0.0.1
20 verbose cwd /home/divyansh/Desktop/Projects/Open Source/freeCodeCamp
21 verbose Linux 5.11.0-37-generic
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "develop"
23 verbose node v14.17.0
24 verbose npm  v6.14.13
25 error code ELIFECYCLE
26 error errno 1
27 error @freecodecamp/freecodecamp@0.0.1 develop: `npm-run-all build:curriculum -p develop:*`
27 error Exit status 1
28 error Failed at the @freecodecamp/freecodecamp@0.0.1 develop script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```

## error
![image](https://user-images.githubusercontent.com/41837037/135507257-c053e187-b717-453a-90fe-8a8904b470e7.png)

I have tried all other solution from switching to nodev14.17.10  to installing libvips for linux (solution to a SO question) and rebuilding sharp, installing gatsby globally, running `npm install --ignore-scripts=false`

**Comment by ieahleen** [comment]
Could you open a topic on the forum in #contributors sub forum? It’s the best place for support on setting up freeCodeCamp locally
