### ISSUE TITLE
unit tests for Python project "main variance standard deviation" are failing

### ISSUE THREAD

**Issue by Bruno-366** [freeCodeCamp/freeCodeCamp#43703]
## Affected page

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/mean-variance-standard-deviation-calculator
https://replit.com/github/freeCodeCamp/boilerplate-mean-variance-standard-deviation-calculator

## Your code

```
======================================================================
ERROR: test_calculate (test_module.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/boilerplate-mean-variance-standard-deviation-calculator/test_module.py", line 10, in test_calculate
    self.assertAlmostEqual(actual, expected, "Expected different output when calling 'calculate()' with '[2,6,2,8,4,0,1,5,7]'")
  File "/usr/lib/python3.8/unittest/case.py", line 937, in assertAlmostEqual
    if first == second:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_calculate2 (test_module.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/boilerplate-mean-variance-standard-deviation-calculator/test_module.py", line 15, in test_calculate2
    self.assertAlmostEqual(actual, expected, "Expected different output when calling 'calculate()' with '[9,1,5,3,3,3,2,9,0]'")
  File "/usr/lib/python3.8/unittest/case.py", line 937, in assertAlmostEqual
    if first == second:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()



```

## Expected behavior

I am sure that I have written an `calculate()` function that should pass the test.
The error seems to rather be with the unit tests themselves, which are using `self.assertAlmostEqual()` on two arrays, and that seems to be raising an ERROR.

## Screenshots

![replit com_@Bruno-366_boilerplate-mean-variance-standard-deviation-calculator (1)](https://user-images.githubusercontent.com/81762173/135767294-ab7fc819-75ea-46c4-98f3-0170e4e685d2.png)

## System

- Device: Desktop
- OS: Windows 10
- Browser: chrome

**Comment by Bruno-366** [comment]
nevermind! forgot to add `.tolist()` to the numpy arrays :)
