### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by yessGlory17** [freeCodeCamp/freeCodeCamp#44479]
Failed loading boot script: /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/boot/certificate.js
Error: Cannot find module '../../../../config/curriculum.json'
Require stack:
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/utils/get-curriculum.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/boot/certificate.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/lib/require.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/lib/compiler.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/index.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/utils/get-curriculum.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._compile (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.newLoader [as .js] (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/boot/certificate.js:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._compile (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/pirates/lib/index.js:99:24)
/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/lib/executor.js:302
      throw err;
      ^

Error: Cannot find module '../../../../config/curriculum.json'
Require stack:
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/utils/get-curriculum.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/boot/certificate.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/lib/require.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/lib/compiler.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/index.js
- /home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/utils/get-curriculum.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._compile (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.newLoader [as .js] (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/boot/certificate.js:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._compile (/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/pirates/lib/index.js:99:24) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/utils/get-curriculum.js',
    '/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/boot/certificate.js',
    '/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/lib/require.js',
    '/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/lib/compiler.js',
    '/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/node_modules/loopback-boot/index.js',
    '/home/ozgur/Masaüstü/Open-Source/freeCodeCamp/api-server/src/server/index.js'
  ]
}

Node.js v17.2.0

OS: Ubuntu 20.04

**Comment by ShaunSHamilton** [comment]
Hello there,

For assistance with setting up freeCodeCamp locally, we recommend you reach out on either the [forum](https://forum.freecodecamp.org/) or the [Chat server](https://chat.freecodecamp.org/). As such, I am going to close this issue.

---

As for this error:
- It usually comes about due to an error during `npm run develop`. We suggest:
  a) Ensure you have the latest changes from `freeCodeCamp/freeCodeCamp`
  b) Run `npm run clean`
  c) Run `npm ci` and try again
- Also, we are not currently supporting Node > 16
- If you are struggling a lot, we suggest trying Gitpod with this repo, as a lot of the steps are automated.


I hope this helps

**Comment by yessGlory17** [comment]
Thank you so much :tada:
