### ISSUE TITLE
Unable to start app on local machine.

### ISSUE THREAD

**Issue by phoenixstormcrow** [FreeCodeCamp/freecodecamp#450]
I've cloned the repo and followed the steps in the 'Getting Started' section of README.md. I'm able to populate the database with `node seed_data/seed.js`, but when I run `gulp`, I get the following error:

```
[14:36:24] Using gulpfile ~/fcc/freecodecamp/gulpfile.js
[14:36:24] Starting 'serve'...
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node ./app.js`
[14:36:25] Finished 'serve' after 1.1 s
[14:36:25] Starting 'sync'...
[14:36:26] Finished 'sync' after 384 ms
[14:36:26] Starting 'default'...
[14:36:26] Finished 'default' after 8.41 μs
[BS] Proxying: http://localhost:3000
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:3001
[BS] External URL: http://192.168.0.5:3001
[BS] Watching files...
Fri, 15 May 2015 21:36:36 GMT uncaughtException: OAuth2Strategy requires a clientID option
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/home/phoenix/fcc/freecodecamp/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:83:34)
    at new Strategy (/home/phoenix/fcc/freecodecamp/node_modules/passport-facebook/lib/strategy.js:55:18)
    at Object.<anonymous> (/home/phoenix/fcc/freecodecamp/config/passport.js:59:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/phoenix/fcc/freecodecamp/app.js:57:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
[gulp] [nodemon] app crashed - waiting for file changes before starting...
```

It seems passport is trying to use the facebook strategy for some reason. It should be using a local strategy, given my .env:
```
MONGOHQ_URL='mongodb://localhost:27017/freecodecamp'
SESSION_SECRET='ANY ENGLISH PHRASE'
MANDRILL_USER='phoenixstormcrow@gmail.com'
MANDRILL_PASSWORD='***********************'
```

I've run both `dropDatabase` and `dropAllUsersFromDatabase` on the db in mongo client, deleted and re-cloned the repo, re-installed npm and bower packages, re-run `node seed_data/seed.js`, and still get this error.

**Comment by phoenixstormcrow** [comment]
One factor that might be relevant is that I switched from signing in to the site using google to using email and password within the past hour.

**Comment by terakilobyte** [comment]
This is because you aren't defining the rest of the variables in your .env file needed. Copy the **entire** file and change stuff as you need. Leaving them with defaults values like 'stuff' is fine if you never use them.

**Comment by phoenixstormcrow** [comment]
Ohhhh okay. Thanks.
