### ISSUE TITLE
Basic Node and Express - Use the .env File Test broken

### ISSUE THREAD

**Issue by DeviousLab** [freeCodeCamp/freeCodeCamp#46836]
### Describe the Issue

When trying to test the 'Use the .env File' challenge, the Replit console crashes and the test fails on FCC's end. I believe this might be a issue similar to #40915.

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/use-the--env-file

### Your code

Link to [Replit](https://replit.com/@DeviousLab/boilerplate-express#myApp.js)
```
let express = require('express');
let app = express();
const path = require('path')


app.use('/', express.static(path.join(__dirname, 'views')))

app.use("/public", express.static(__dirname + "/public"));

app.get('/json', (req, res) => {
 res.json(process.env.MESSAGE_STYLE=="uppercase" ? {"message": "HELLO JSON"}: {"message": "Hello json"})
})
```

### Expected behavior

Expected test to pass and detect the endpoint /json change according to the environment variable MESSAGE_STYLE.

### Screenshots

Confirmed secret
![image](https://user-images.githubusercontent.com/53790060/178122039-c7425d0b-933b-4202-8c85-8f11a8467880.png)

### System

- Device: [Lenovo Thinkpad T460S]
- OS: [Fedora 35 KDE]
- Browser: [Brave]
- Version: [1.40.113]

### Additional context

Error message:
```
> npm start

> fcc-learn-node-with-express@0.1.0 start
> node server.js

Node is listening on port 3000...
*
*
https://www.freecodecamp.org
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/runner/boilerplate-express-1/node_modules/fcc-express-bground/index.js:91:26
    at IncomingMessage.<anonymous> (/home/runner/boilerplate-express-1/node_modules/fcc-express-bground/index.js:33:7)
    at IncomingMessage.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:141:24)
    at Socket.socketOnData (node:_http_client:487:22)
    at Socket.emit (node:events:394:28)
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/runner/boilerplate-express-1/node_modules/fcc-express-bground/index.js:99:28
    at IncomingMessage.<anonymous> (/home/runner/boilerplate-express-1/node_modules/fcc-express-bground/index.js:33:7)
    at IncomingMessage.emit (node:events:394:28)
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1012:34)
    at resume_ (node:internal/streams/readable:993:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
node:_http_outgoing:573
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at ServerResponse.header (/home/runner/boilerplate-express-1/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/home/runner/boilerplate-express-1/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/runner/boilerplate-express-1/node_modules/express/lib/response.js:267:15)
    at /home/runner/boilerplate-express-1/node_modules/fcc-express-bground/index.js:108:15
    at IncomingMessage.<anonymous> (/home/runner/boilerplate-express-1/node_modules/fcc-express-bground/index.js:33:7)
    at IncomingMessage.emit (node:events:394:28)
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1012:34) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
exit status 1
```

**Comment by DeviousLab** [comment]
This issue can be disregarded as after running `npm update --save` as suggested by [FCC](https://forum.freecodecamp.org/t/use-the-env-file-issue-resolved/444454) the error message no longer appears and the test functions properly.

It seems that the starter code for these challenges needs to be updated though:
![image](https://user-images.githubusercontent.com/53790060/178148509-e7e0922b-cc9c-40d8-ab42-34642fd0ceea.png)

**Comment by gikf** [comment]
Thank you for reporting this issue.

The origin of the issue should be fixed per https://github.com/freeCodeCamp/boilerplate-express/pull/96

Thank you and happy coding.
