### ISSUE TITLE
Can't run curriculum tests in gitpod

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#52453]
_Originally posted by @eric-do in https://github.com/freeCodeCamp/freeCodeCamp/issues/52451#issuecomment-1833058838_

When you try to run `pnpm test:curriculum` in gitpod, it doesn't work. Here's copy of the error:

```
> @freecodecamp/curriculum@0.0.0-next.4 test /workspace/freeCodeCamp/curriculum
> ts-node ./node_modules/mocha/bin/mocha.js --delay --exit --reporter progress --bail

Error: Failed to launch the browser process!
/workspace/freeCodeCamp/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/workspace/freeCodeCamp/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/src/node/BrowserRunner.ts:223:9)
    at Interface.<anonymous> (/workspace/freeCodeCamp/node_modules/.pnpm/puppeteer@10.4.0/node_modules/puppeteer/src/node/BrowserRunner.ts:209:50)
    at Interface.emit (node:events:526:35)
    at Interface.emit (node:domain:488:12)
    at Interface.close (node:internal/readline/interface:527:10)
    at Socket.onend (node:internal/readline/interface:253:10)
    at Socket.emit (node:events:526:35)
    at Socket.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
 ELIFECYCLE  Test failed. See above for more details.
 
```

In my response to the linked comment, I shared [a link to part of that troubleshooting suggestion in the error.](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) Seems like there might be some things to try in there.

**Comment by ShaunSHamilton** [comment]
Did you run `pnpm run cypress:install-build-tools`?
https://github.com/freeCodeCamp/freeCodeCamp/blob/d6cd19f567a66acc76e0ccfb4163b176ccdc22ee/cypress-install.sh#L16-L50

**Comment by moT01** [comment]
That did the trick, thanks @ShaunSHamilton 👍
