### ISSUE TITLE
a problem with mongodb

### ISSUE THREAD

**Issue by xuzaixian** [FreeCodeCamp/FreeCodeCamp#5389]
i got a problem when i install
npm run only-once
then:
```
seeding database


Error: Required MongoStore option `db` missing or is not a string.
    at buildUrlFromOptions (/home/hyuni/freecodecamp/node_modules/connect-mongo/lib/connect-mongo.js:163:15)
    at new MongoStore (/home/hyuni/freecodecamp/node_modules/connect-mongo/lib/connect-mongo.js:250:7)
    at sessionsMiddleware (/home/hyuni/freecodecamp/server/middlewares/sessions.js:12:12)
    at EventEmitter.proto.middlewareFromConfig (/home/hyuni/freecodecamp/node_modules/loopback/lib/server-app.js:67:25)
    at /home/hyuni/freecodecamp/node_modules/loopback-boot/lib/executor.js:329:9
    at Array.forEach (native)
    at setupMiddleware (/home/hyuni/freecodecamp/node_modules/loopback-boot/lib/executor.js:319:14)
    at execute (/home/hyuni/freecodecamp/node_modules/loopback-boot/lib/executor.js:34:3)
    at bootLoopBackApp (/home/hyuni/freecodecamp/node_modules/loopback-boot/index.js:140:3)
    at Object.<anonymous> (/home/hyuni/freecodecamp/server/server.js:39:1)
```
TAT
i need some help
i don't know anything about MongoDB...

**Comment by raisedadead** [comment]
@xuzaixian : Have you created a directory structure like : `/home/user/path/to/data/db` ?

What I mean to say that before running node seed, you need to run `mongod` in a separate terminal with some `dbpath` and the "data" & "db" directories should exist!

After doing that you need to run the below command :

`$ mongod --dbpath ./data/db/`

Where your directory would look like this:
```
user/path
`-- data
    `-- db
```

**Comment by BerkeleyTrue** [comment]
@xuzaixian Did you populate your .env file?

**Comment by xuzaixian** [comment]
@raisedadead sorry.I did.but it still cannot work.
```
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten] MongoDB starting : pid=4002 port=27017 dbpath=./data/db 64-bit host=hyuni-GE60-0NC-GE60-0ND
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten] db version v3.2.0
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten] git version: 45d947729a0315accb6d4f15a6b06be6d9c19fe7
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten] allocator: tcmalloc
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten] modules: none
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten] build environment:
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten]     distmod: ubuntu1404
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten]     distarch: x86_64
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten]     target_arch: x86_64
2015-12-21T10:59:28.502+0800 I CONTROL  [initandlisten] options: { storage: { dbPath: "./data/db" } }
2015-12-21T10:59:28.526+0800 I -        [initandlisten] Detected data files in ./data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2015-12-21T10:59:28.526+0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=4G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2015-12-21T10:59:29.067+0800 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2015-12-21T10:59:29.067+0800 I CONTROL  [initandlisten] 
2015-12-21T10:59:29.067+0800 I CONTROL  [initandlisten] 
2015-12-21T10:59:29.067+0800 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2015-12-21T10:59:29.067+0800 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-12-21T10:59:29.067+0800 I CONTROL  [initandlisten] 
2015-12-21T10:59:29.067+0800 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2015-12-21T10:59:29.068+0800 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-12-21T10:59:29.068+0800 I CONTROL  [initandlisten] 
2015-12-21T10:59:29.069+0800 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory './data/db/diagnostic.data'
2015-12-21T10:59:29.069+0800 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
2015-12-21T10:59:29.070+0800 I NETWORK  [initandlisten] waiting for connections on port 27017
```
is it supposed to look like this ? when i launch the mongodb?

**Comment by BerkeleyTrue** [comment]
> 2015-12-21T10:59:29.070+0800 I NETWORK  [initandlisten] waiting for connections on port 27017

yes. It is waiting for connections

**Comment by xuzaixian** [comment]
@BerkeleyTrue but freecodecamp is still not working

**Comment by BerkeleyTrue** [comment]
your .env file should have this line 
`MONGOHQ_URL='mongodb://localhost:27017/freecodecamp'`

**Comment by xuzaixian** [comment]
@BerkeleyTrue 
yes.this is my .env
```
NGOHQ_URL='mongodb://localhost:27017/freecodecamp'

MANDRILL_PASSWORD=stuff
MANDRILL_USER=stuff
```
everything seems ok.but it just cannot work.

**Comment by BerkeleyTrue** [comment]
Are you still getting the same error as above?

**Comment by xuzaixian** [comment]
@BerkeleyTrue yes ...it's driving me crazy

**Comment by alistermada** [comment]
@xuzaixian Your .env says `NGOHQ_URL` when it should be `MONGO_URL`

**Comment by raisedadead** [comment]
Wow @alistermada ! I missed that. Lol!
@xuzaixian : Chang it to what @alistermada has pointed out. And try again.

**Comment by SaintPeter** [comment]
Closing as this appears to be resolved.  Feel free to reopen if you have further issue.

You can get additional assistance in running the site in the [HelpContributors Chat Room](https://gitter.im/FreeCodeCamp/HelpContributors?utm_source=share-link&utm_medium=link&utm_campaign=share-link) on Gitter.

Happy Coding!

**Comment by xuzaixian** [comment]
@alistermada @raisedadead 
LOL!  
it works, thanks ~
