### ISSUE TITLE
#time-left not recognized in 25 + 5 clock React certification

### ISSUE THREAD

**Issue by Emeryx** [freeCodeCamp/freeCodeCamp#54379]
### Describe the Issue

I still haven't finished the project at all, I'm working on Visual Studio Code using the bundle JS provided for testing the code and I found out that it doesn't pass the 8th test:

"User Story #8: I can see an element with corresponding id="time-left". NOTE: Paused or running, the value in this field should always be displayed in mm:ss format (i.e. 25:00)."

For my #time-left and timer in general I use a node package called react-circular-progressbar for design purposes.

My #time-left goes inside the circular progressbar for better UX

Since I can't assign an id directly using the node package I had to do it myself. The ID is presented after the files are compiled

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-25--5-clock

### Your code

HTML after compiling looks like this:

`<text class="CircularProgressbar-text" x="50" y="50" id="time-left" style="fill: rgb(250, 250, 250); font-size: 24px;">25:00</text>`

Here is my custom assignment to the element displaying the text in my Timer.tsx
`
    useLayoutEffect(() => {
        console.log("inner html set");
        const text = document.querySelector(".CircularProgressbar-text");
        console.log(text);
        if (!text) return;
        text.setAttribute("id", "time-left");
    },[]);
`

Using useEffect() instead has no changes 

If you wish to view my full (Very WIP) code it can be found here

https://github.com/Emeryx/Pomodoro

### Expected behavior

I expected to pass the 8th user story because an element with the ID "time-left" exists and displays the time in a format of mm:ss

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/e8dedb06-717b-457f-82c2-9b24b2c8adf4)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

The error to the test is as follows:

`Bad time string undefined
Error: Bad time string undefined
    at l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:581:167664)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:581:171401
    at p (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:581:94539)
    at Generator.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:581:95876)
    at Generator.next (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:581:94902)
    at r (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1169)
    at s (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1380)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1439
    at new Promise (<anonymous>)
    at n.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1320)`

**Comment by Emeryx** [comment]
I just discovered that adding innerText to the element presented me with a different error

`time-left is not formatted correctly: expected '01' to equal '25'
AssertionError: time-left is not formatted correctly: expected '01' to equal '25'
    at Proxy.h (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:531:2123)
    at Proxy.u (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:407:130)
    at n.strictEqual (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:556:655)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:581:171389
    at p (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:581:94539)
    at Generator.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:581:95876)
    at Generator.next (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:581:94902)
    at r (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1169)
    at s (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1380)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:1:1439`

Which is a logic issue and I can continue doing my project, Problem solved!
