### ISSUE TITLE
Portfolio E2E tests are failing on WebKit

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#56828]
The E2E tests for the new portfolio page keep failing.

```
1) [webkit] › portfolio.spec.ts:79:7 › Add Portfolio Item › The description has validation ───────

    Test timeout of 15000ms exceeded.

    Error: locator.fill: Test timeout of 15000ms exceeded.
    Call log:
      - waiting for getByLabel('Description')


      83 |     await page
      84 |       .getByLabel(translations.settings.labels.description)
    > 85 |       .fill(
         |        ^
      86 |         'This is the longest description you will ever see in your entire life, you will never see such a long description again. This is the longest description in existence. Nothing will ever come close to be being so long again in the entire history of the world. I only have 30 characters left.'
      87 |       );
      88 |     await expect(page.getByTestId('description-validation')).toContainText(

        at /home/runner/work/freeCodeCamp/freeCodeCamp/e2e/portfolio.spec.ts:85:8

    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    Test timeout of 15000ms exceeded.

    Error: locator.fill: Test timeout of 15000ms exceeded.
    Call log:
      - waiting for getByLabel('Description')


      83 |     await page
      84 |       .getByLabel(translations.settings.labels.description)
    > 85 |       .fill(
         |        ^
      86 |         'This is the longest description you will ever see in your entire life, you will never see such a long description again. This is the longest description in existence. Nothing will ever come close to be being so long again in the entire history of the world. I only have 30 characters left.'
      87 |       );
      88 |     await expect(page.getByTestId('description-validation')).toContainText(

        at /home/runner/work/freeCodeCamp/freeCodeCamp/e2e/portfolio.spec.ts:85:8

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    playwright/test-results/portfolio-Add-Portfolio-Item-The-description-has-validation-webkit-retry1/trace.zip
    Usage:

        npx playwright show-trace playwright/test-results/portfolio-Add-Portfolio-Item-The-description-has-validation-webkit-retry1/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

    Retry #2 ───────────────────────────────────────────────────────────────────────────────────────

    Test timeout of 15000ms exceeded.

    Error: locator.fill: Test timeout of 15000ms exceeded.
    Call log:
      - waiting for getByLabel('Description')


      83 |     await page
      84 |       .getByLabel(translations.settings.labels.description)
    > 85 |       .fill(
         |        ^
      86 |         'This is the longest description you will ever see in your entire life, you will never see such a long description again. This is the longest description in existence. Nothing will ever come close to be being so long again in the entire history of the world. I only have 30 characters left.'
      87 |       );
      88 |     await expect(page.getByTestId('description-validation')).toContainText(

        at /home/runner/work/freeCodeCamp/freeCodeCamp/e2e/portfolio.spec.ts:85:8

  2) [webkit] › portfolio.spec.ts:51:7 › Add Portfolio Item › The url has validation ───────────────

    Test timeout of 15000ms exceeded.

    Error: locator.fill: Test timeout of 15000ms exceeded.
    Call log:
      - waiting for getByLabel('URL')


      53 |       .getByRole('button', { name: 'Add a new portfolio Item' })
      54 |       .click();
    > 55 |     await page.getByLabel(translations.settings.labels.url).fill('T');
         |                                                             ^
      56 |     await expect(page.getByTestId('url-validation')).toContainText(
      57 |       'Please use a valid URL'
      58 |     );

        at /home/runner/work/freeCodeCamp/freeCodeCamp/e2e/portfolio.spec.ts:55:61

    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    Test timeout of 15000ms exceeded.

    Error: locator.fill: Test timeout of 15000ms exceeded.
    Call log:
      - waiting for getByLabel('URL')


      53 |       .getByRole('button', { name: 'Add a new portfolio Item' })
      54 |       .click();
    > 55 |     await page.getByLabel(translations.settings.labels.url).fill('T');
         |                                                             ^
      56 |     await expect(page.getByTestId('url-validation')).toContainText(
      57 |       'Please use a valid URL'
      58 |     );

        at /home/runner/work/freeCodeCamp/freeCodeCamp/e2e/portfolio.spec.ts:55:61

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    playwright/test-results/portfolio-Add-Portfolio-Item-The-url-has-validation-webkit-retry1/trace.zip
    Usage:

        npx playwright show-trace playwright/test-results/portfolio-Add-Portfolio-Item-The-url-has-validation-webkit-retry1/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

  3) [webkit] › portfolio.spec.ts:121:7 › Add Portfolio Item › It should be possible to add a portfolio item 

    Error: Timed out 5000ms waiting for expect(locator).toBeDisabled()

    Locator: getByRole('button', { name: 'Add a new portfolio Item' })
    Expected: disabled
    Received: enabled
    Call log:
      - expect.toBeDisabled with timeout 5000ms
      - waiting for getByRole('button', { name: 'Add a new portfolio Item' })
      -   locator resolved to <button type="button" aria-disabled="false" class=" relative inline-block mt-[0.5px] border-solid border-3 active:before:w-full active:before:h-full active:before:absolute active:before:inset-0 active:before:border-3 active:before:border-transparent active:before:bg-gray-[90](https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11501412212/job/32015928092#step:14:91)0 active:before:opacity-20 text-center cursor-pointer no-underline block w-full bg-background-quaternary text-foreground-secondary border-foreground-secondary hover:bg-foreground-primary hover:text-background-primary hover:border-fo…>Add a new portfolio Item</button>
      -   unexpected value "enabled"
      -   locator resolved to <button type="button" aria-disabled="false" class=" relative inline-block mt-[0.5px] border-solid border-3 active:before:w-full active:before:h-full active:before:absolute active:before:inset-0 active:before:border-3 active:before:border-transparent active:before:bg-gray-900 active:before:opacity-20 text-center cursor-pointer no-underline block w-full bg-background-quaternary text-foreground-secondary border-foreground-secondary hover:bg-foreground-primary hover:text-background-primary hover:border-fo…>Add a new portfolio Item</button>
      -   unexpected value "enabled"
      -   locator resolved to <button type="button" aria-disabled="false" class=" relative inline-block mt-[0.5px] border-solid border-3 active:before:w-full active:before:h-full active:before:absolute active:before:inset-0 active:before:border-3 active:before:border-transparent active:before:bg-gray-900 active:before:opacity-20 text-center cursor-pointer no-underline block w-full bg-background-quaternary text-foreground-secondary border-foreground-secondary hover:bg-foreground-primary hover:text-background-primary hover:border-fo…>Add a new portfolio Item</button>
      -   unexpected value "enabled"
      -   locator resolved to <button type="button" aria-disabled="false" class=" relative inline-block mt-[0.5px] border-solid border-3 active:before:w-full active:before:h-full active:before:absolute active:before:inset-0 active:before:border-3 active:before:border-transparent active:before:bg-gray-900 active:before:opacity-20 text-center cursor-pointer no-underline block w-full bg-background-quaternary text-foreground-secondary border-foreground-secondary hover:bg-foreground-primary hover:text-background-primary hover:border-fo…>Add a new portfolio Item</button>
      -   unexpected value "enabled"
      -   locator resolved to <button type="button" aria-disabled="false" class=" relative inline-block mt-[0.5px] border-solid border-3 active:before:w-full active:before:h-full active:before:absolute active:before:inset-0 active:before:border-3 active:before:border-transparent active:before:bg-gray-900 active:before:opacity-20 text-center cursor-pointer no-underline block w-full bg-background-quaternary text-foreground-secondary border-foreground-secondary hover:bg-foreground-primary hover:text-background-primary hover:border-fo…>Add a new portfolio Item</button>
      -   unexpected value "enabled"
      -   locator resolved to <button type="button" aria-disabled="false" class=" relative inline-block mt-[0.5px] border-solid border-3 active:before:w-full active:before:h-full active:before:absolute active:before:inset-0 active:before:border-3 active:before:border-transparent active:before:bg-gray-900 active:before:opacity-20 text-center cursor-pointer no-underline block w-full bg-background-quaternary text-foreground-secondary border-foreground-secondary hover:bg-foreground-primary hover:text-background-primary hover:border-fo…>Add a new portfolio Item</button>
      -   unexpected value "enabled"
      -   locator resolved to <button type="button" aria-disabled="false" class=" relative inline-block mt-[0.5px] border-solid border-3 active:before:w-full active:before:h-full active:before:absolute active:before:inset-0 active:before:border-3 active:before:border-transparent active:before:bg-gray-900 active:before:opacity-20 text-center cursor-pointer no-underline block w-full bg-background-quaternary text-foreground-secondary border-foreground-secondary hover:bg-foreground-primary hover:text-background-primary hover:border-fo…>Add a new portfolio Item</button>
      -   unexpected value "enabled"
      -   locator resolved to <button type="button" aria-disabled="false" class=" relative inline-block mt-[0.5px] border-solid border-3 active:before:w-full active:before:h-full active:before:absolute active:before:inset-0 active:before:border-3 active:before:border-transparent active:before:bg-gray-900 active:before:opacity-20 text-center cursor-pointer no-underline block w-full bg-background-quaternary text-foreground-secondary border-foreground-secondary hover:bg-foreground-primary hover:text-background-primary hover:border-fo…>Add a new portfolio Item</button>
      -   unexpected value "enabled"
      -   locator resolved to <button type="button" aria-disabled="false" class=" relative inline-block mt-[0.5px] border-solid border-3 active:before:w-full active:before:h-full active:before:absolute active:before:inset-0 active:before:border-3 active:before:border-transparent active:before:bg-gray-900 active:before:opacity-20 text-center cursor-pointer no-underline block w-full bg-background-quaternary text-foreground-secondary border-foreground-secondary hover:bg-foreground-primary hover:text-background-primary hover:border-fo…>Add a new portfolio Item</button>
      -   unexpected value "enabled"


      125 |     await expect(
      126 |       page.getByRole('button', { name: 'Add a new portfolio Item' })
    > 127 |     ).toBeDisabled();
          |       ^
      128 |
      129 |     await page
      130 |       .getByLabel(translations.settings.labels.title)

        at /home/runner/work/freeCodeCamp/freeCodeCamp/e2e/portfolio.spec.ts:127:7

  4) [webkit] › shortcuts-modal.spec.ts:78:5 › has a button to disable or enable keyboard shortcuts 

    Error: Timed out 5000ms waiting for expect(locator).toBeFocused()

    Locator: getByTestId('hotkeys')
    Expected: focused
    Received: inactive
    Call log:
      - expect.toBeFocused with timeout 5000ms
      - waiting for getByTestId('hotkeys')
      -   locator resolved to <div tabindex="-1" id="editor-layout" data-playwright-test-label="hotkeys">…</div>
      -   unexpected value "not focused"
      -   locator resolved to <div tabindex="-1" id="editor-layout" data-playwright-test-label="hotkeys">…</div>
      -   unexpected value "not focused"
      -   locator resolved to <div tabindex="-1" id="editor-layout" data-playwright-test-label="hotkeys">…</div>
      -   unexpected value "not focused"
      -   locator resolved to <div tabindex="-1" id="editor-layout" data-playwright-test-label="hotkeys">…</div>
      -   unexpected value "not focused"
      -   locator resolved to <div tabindex="-1" id="editor-layout" data-playwright-test-label="hotkeys">…</div>
      -   unexpected value "not focused"
      -   locator resolved to <div tabindex="-1" id="editor-layout" data-playwright-test-label="hotkeys">…</div>
      -   unexpected value "not focused"
      -   locator resolved to <div tabindex="-1" id="editor-layout" data-playwright-test-label="hotkeys">…</div>
      -   unexpected value "not focused"
      -   locator resolved to <div tabindex="-1" id="editor-layout" data-playwright-test-label="hotkeys">…</div>
      -   unexpected value "not focused"
      -   locator resolved to <div tabindex="-1" id="editor-layout" data-playwright-test-label="hotkeys">…</div>
      -   unexpected value "not focused"


      29 |   // capture the keyboard shortcuts
      30 |   await getEditors(page).press('Escape');
    > 31 |   await expect(page.getByTestId('hotkeys')).toBeFocused();
         |                                             ^
      32 |   await page.keyboard.press('Shift+?');
      33 | };
      34 |

        at openModal (/home/runner/work/freeCodeCamp/freeCodeCamp/e2e/shortcuts-modal.spec.ts:31:45)
        at /home/runner/work/freeCodeCamp/freeCodeCamp/e2e/shortcuts-modal.spec.ts:81:3

    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toBeVisible()

    Locator: getByText(/We have updated your keyboard shortcuts settings/)
    Expected: visible
    Received: <element(s) not found>
    Call log:
      - expect.toBeVisible with timeout 5000ms
      - waiting for getByText(/We have updated your keyboard shortcuts settings/)


      [93](https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11501412212/job/32015928092#step:14:94) |   await expect(
      94 |     page.getByText(new RegExp(translations.flash['keyboard-shortcut-updated']))
    > [95](https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11501412212/job/32015928092#step:14:96) |   ).toBeVisible();
         |     ^
      [96](https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11501412212/job/32015928092#step:14:97) |
      [97](https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11501412212/job/32015928092#step:14:98) |   await page.keyboard.press('Shift+?');
      [98](https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11501412212/job/32015928092#step:14:99) |

        at /home/runner/work/freeCodeCamp/freeCodeCamp/e2e/shortcuts-modal.spec.ts:95:5

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    playwright/test-results/shortcuts-modal-has-a-butt-57ee7-r-enable-keyboard-shortcuts-webkit-retry1/trace.zip
    Usage:

        npx playwright show-trace playwright/test-results/shortcuts-modal-has-a-butt-57ee7-r-enable-keyboard-shortcuts-webkit-retry1/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

  Slow test file: [webkit] › username-change.spec.ts (34.1s)
  Slow test file: [webkit] › lower-jaw.spec.ts (30.8s)
  Slow test file: [webkit] › output.spec.ts (29.2s)
  Slow test file: [webkit] › completion-modal.spec.ts (27.5s)
  Slow test file: [webkit] › challenge-reset-modal.spec.ts (27.2s)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    [webkit] › portfolio.spec.ts:79:7 › Add Portfolio Item › The description has validation ────────
  3 flaky
    [webkit] › portfolio.spec.ts:51:7 › Add Portfolio Item › The url has validation ────────────────
    [webkit] › portfolio.spec.ts:[121](https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11501412212/job/32015928092#step:14:122):7 › Add Portfolio Item › It should be possible to add a portfolio item 
    [webkit] › shortcuts-modal.spec.ts:78:5 › has a button to disable or enable keyboard shortcuts ─
  25 skipped
  342 passed (13.9m)
Error: Process completed with exit code 1.

















































































```

**Comment by ojeytonwilliams** [comment]
Just webkit, right?

@Sembauke, I think you worked on these most recently. Could you take a look?

**Comment by Sembauke** [comment]
Sure, no problem/

**Comment by brambhattabhishek** [comment]
1. Timeout Exceeded for Locator.fill

Potential Solutions -->

#Increase Timeout :- You can increase the timeout for the specific test or action`await page.getByLabel(translations.settings.labels.description, { timeout: 30000 }).fill('...');
`
#Check Visibility :-  Ensure the element is visible and enabled `await expect(page.getByLabel(translations.settings.labels.description)).toBeVisible();
`
2. Button Not Being Disabled

Potential Solutions --> 

#Debug Validation Logic :- Check the logic that controls when the button is enabled or disabled. Ensure that it correctly reflects the state of the input fields

#Add Explicit Wait:- Sometimes adding an explicit wait for the button's state to change can help `await expect(page.getByRole('button', { name: 'Add a new portfolio Item' })).toBeDisabled({ timeout: 10000 });
`

3. Focus Not Found 

Potential Solutions-->

#Ensure Focus : Before asserting that the element is focused, ensure it is focused. You can explicitly focus on the element if needed `await page.getByTestId('hotkeys').focus();
await expect(page.getByTestId('hotkeys')).toBeFocused();
`

**Comment by Sembauke** [comment]
@ilenia-magoni  The portfolio test should now be a little more stable. I will be closing this. I did not directly want to reference the pull-request as it might not have closed the issue.

Please re-open if you can find more stability issues with the portfolio tests. Please make sure that you are on the latest main.

**Comment by ilenia-magoni** [comment]
@Sembauke the main branch has still failures: https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/11553184761/job/32154422915

**Comment by Sembauke** [comment]
please re-open if failing after #57428
