### ISSUE TITLE
Got blank screen instead of playing video

### ISSUE THREAD

**Issue by Arasan-Github** [freeCodeCamp/freeCodeCamp#57095]
### Describe the Issue

While I learning my A2 English for developers I stumbled into this issue that showed a blank page and I have checked the console in the browser and it showed an error as ```navigation.js:127 TypeError: Cannot read properties of null (reading 'map')
    at A (show.tsx:160:15)
    at Ji (react-dom.production.min.js:153:146)
    at Sa (react-dom.production.min.js:261:496)
    at Cu (react-dom.production.min.js:246:265)
    at Tu (react-dom.production.min.js:246:194)
    at yu (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Kl (react-dom.production.min.js:122:325)
    at Zl (react-dom.production.min.js:123:61)```

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-how-to-discuss-roles-and-responsibilies/dialogue-5-brian-and-sophie-talk-about-responsibilities

### Steps to Reproduce

Just open the "Learn How to Discuss Roles and responsibilities"  and open the "[Dialogue 5: Brian And Sophie Talk about Responsibilities](https://www.freecodecamp.org/learn/a2-english-for-developers/learn-how-to-discuss-roles-and-responsibilies/dialogue-5-brian-and-sophie-talk-about-responsibilities)" to reproduce it

### Recommended fix or suggestions

Some value is missing in the code it seems in the TSX file I guess

### Screenshots

![Image](https://github.com/user-attachments/assets/4f9d5e8c-ec30-46c1-b971-a24e00a2febc)

**Comment by gikf** [comment]
Looks like it affects all dialogs.

**Comment by ShaunSHamilton** [comment]
I expect this to be fixed by: https://github.com/freeCodeCamp/freeCodeCamp/pull/57086 (not deployed)
