### ISSUE TITLE
Authorization Error with GitHub OAuth API, when using Clementine JS in c9 cloud box

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/FreeCodeCamp#5808]
Hi, I would like to report an issue regarding authorization via GitHub with c9 cloudbox.

I was starting the Timestamp-Microservice API project, and followed the *Waypoint* that came before it.

I followed the instructions provided in the waypoint on how to set up Clementine JS on c9 cloud; and every time I tried to login after that using GitHub; it threw this error:

```
AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.
    at Strategy.OAuth2Strategy.authenticate (/home/ubuntu/workspace/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:126:25)
    at attempt (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/workspace/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/ubuntu/workspace/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/workspace/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:271:10)
    at SessionStrategy.strategy.pass (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:325:9)
    at SessionStrategy.authenticate (/home/ubuntu/workspace/node_modules/passport/lib/strategies/session.js:71:10)
    at attempt (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:312:13)
```

I found a fix for this after a while.

In the `.env` file, the `APP_URL` variable was set as `https://timestamp-microservice-alayek.c9users.io`; which causes the error.

When I appended a trailing slash at the end of it: `https://timestamp-microservice-alayek.c9users.io/`, it worked fine.

Kindly update the instructions if this is a bug. A lot of students could potentially face this issue.

**Comment by AkiraLaine** [comment]
@alayek If your fix works, please close this issue. Also, ClementineJS is not required for any of the API Basejump.

**Comment by alayek** [comment]
Thanks @AkiraLaine, but don't you guys need a PR to update the instructions to explicitly state the trailing slash?

**Comment by ltegman** [comment]
@alayek The trailing slash is already in the example, so no correction is needed. Thanks and happy coding!

**Comment by cd-Zero** [comment]
.env file's APP_URL must equal the GitHub submitted Authorization callback URL 

to fix copy and paste APP_URL  into the Authorization callback URL when updating application on GitHub

**Comment by dotm** [comment]
I just want to add: make sure you restart the 'node server.js' after you change the .env file (to update the env settings)

**Comment by FMGordillo** [comment]
It seems that FreeCodeCamp guide has left something!
You need the env var "redirect_uri", it worked for me!

My example

`
APP_URL=https://dynamicwebapp-1-laspark.c9users.io/
redirect_uri=https://dynamicwebapp-1-laspark.c9users.io/auth/github/callback
`
