### ISSUE TITLE
Error:cannot find module 'babel/register'

### ISSUE THREAD

**Issue by NateLing** [FreeCodeCamp/FreeCodeCamp#6336]
```CMD
>node seed\index.js
module.js:328
    throw err;
    ^

Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\Lee\NateLing\FreeCodeCamp\seed\index.js:2:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Comment by BerkeleyTrue** [comment]
Wipe out your node modules and then npm install again.

**Comment by QuincyLarson** [comment]
The command to do what @BerkeleyTrue mentioned (within your Free Code Camp directory) is:
```
rm -rf node_modules  
```
