### ISSUE TITLE
learnyoumongo install errors

### ISSUE THREAD

**Issue by nikrb** [FreeCodeCamp/FreeCodeCamp#6742]
learnyoumongo displays errors (below) during install. Reran with sudo ... but still same errors.
Being a nuub it's largely gobbledy-gook to me. 
learnyoumongo seems to run ok so soldiering on.

```
knik:~/workspace $ npm install learnyoumongo -g
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
\
> kerberos@0.0.18 install /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:36:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:37:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:362:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:930:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
/usr/bin/ld: cannot find -lkrb5
/usr/bin/ld: cannot find -lgssapi_krb5
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/kerberos.node] Error 1
make: Leaving directory `/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/mongodb/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-c9
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
/home/ubuntu/.nvm/versions/node/v4.1.1/bin/learnyoumongo -> /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/learnyoumongo.js
learnyoumongo@3.0.1 /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo
├── chalk@1.0.0 (ansi-styles@2.1.0, escape-string-regexp@1.0.4, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
├── workshopper-exercise@2.3.0 (after@0.8.1, visualwidth@0.0.1, chalk@0.4.0, tuple-stream@0.0.2, split@0.3.3, xtend@2.1.2, through2@0.4.2, i18n-core@1.3.3)
├── workshopper@2.5.0 (map-async@0.1.1, xtend@3.0.0, visualwidth@0.0.1, chalk@0.4.0, mkdirp@0.3.5, colors-tmpl@0.1.1, i18n-core@1.3.3, optimist@0.6.1, terminal-menu@2.1.1, msee@0.1.2)
└── mongodb@2.0.55 (readable-stream@1.0.31, es6-promise@2.1.1, kerberos@0.0.18, mongodb-core@1.2.31)
```

**Comment by SaintPeter** [comment]
Did you try running it?   Despite all of the errors it still looks like it installed.

You're running on a local dev environment, rather than on C9?

**Comment by nikrb** [comment]
I'm using C9.
I did say it seemed to be working so I was continuing.
All db's listed as (empty) except local, which doesn't have a parrots collection.
The original download instruction was to import the data perhaps? This isn't the place for another question, struggling forwards :)

**Comment by SaintPeter** [comment]
`learnyoumongo` actually puts the collection in place only while you're running, the removes it as soon as its done.  You can run `learnyoumongo test <scriptname>` to run it under test conditions without the `verify` step, if I remember correctly.

**Comment by ltegman** [comment]
This is normal behaviour for learnyoumongo and kerberos build errors are not uncommon and can be ignored unless you are using kerberos (most mongo DBs are not). Closing as not an issue. Further issues with learnyoumongo should be filed on [their repo](https://github.com/evanlucas/learnyoumongo). Thanks and happy coding!

**Comment by nikrb** [comment]
thanx for the feedback guys. Checked [their issues](https://github.com/evanlucas/learnyoumongo/issues) and it seems this is up in the air atm.
FYI I've tried learnyoumongo with test, run and verify but no luck. There is also a suggestion of redoing steps 1 and 2 but no luck there either.
