### ISSUE TITLE
Ho-To-NPM #10 verification throws error

### ISSUE THREAD

**Issue by Xenwar** [FreeCodeCamp/FreeCodeCamp#7073]
Challenge [Save your Code Revisions Forever with Git](http://www.freecodecamp.com/challenges/save-your-code-revisions-forever-with-git) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Run all steps #1 to #10
run how-to-npm verify
Expected:
Either success Or Failre
![module js](https://cloud.githubusercontent.com/assets/12200849/13089973/e5de1064-d4fb-11e5-9b54-f8b81809b67e.png)

current result
exception thrown 

module.js:338
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/appstore/body.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/index.js:86:8)

**Comment by bugron** [comment]
@Xenwar thanks for posting. `git-it` is a nodeschool module and there is an open issue https://github.com/nodeschool/discussions/issues/1642 so continue your discussion there, thanks. Closing.

**Comment by QuincyLarson** [comment]
Hi @Xenwar, thank you for reporting this. HowToNPM is practically abandonware. I think we'll need to fork it and fix a lot of these bugs. I've created a new issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7080

**Comment by QuincyLarson** [comment]
@bugron by the way, this issue isn't about git-it - it's about HowToNPM

**Comment by bugron** [comment]
Huh, my bad, sorry, not sure where I was looking)) 
https://github.com/nodeschool/discussions/issues/1558
