### ISSUE TITLE
flyer Error!

### ISSUE THREAD

**Issue by NateLing** [FreeCodeCamp/FreeCodeCamp#8251]
```json
{
    "error": {
        "name": "Error",
        "status": 404,
        "message": "Unknown \"flyer\" id \"undefined\".",
        "statusCode": 404,
        "code": "MODEL_NOT_FOUND",
        "stack": "Error: Unknown \"flyer\" id \"undefined\".\n    at Function.convertNullToNotFoundError (E:\\51freecode\\FreeCodeCamp\\node_modules\\loopback\\lib\\persisted-model.js:81:17)\n    at invokeRestAfter (E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\lib\\rest-adapter.js:453:25)\n    at E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\node_modules\\async\\lib\\async.js:607:21\n    at E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\node_modules\\async\\lib\\async.js:246:17\n    at iterate (E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\node_modules\\async\\lib\\async.js:146:13)\n    at E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\node_modules\\async\\lib\\async.js:157:25\n    at E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\node_modules\\async\\lib\\async.js:248:21\n    at E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\node_modules\\async\\lib\\async.js:612:34\n    at interceptInvocationErrors (E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\lib\\remote-objects.js:681:22)\n    at E:\\51freecode\\FreeCodeCamp\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:154:25\n    at E:\\51freecode\\FreeCodeCamp\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:154:25\n    at E:\\51freecode\\FreeCodeCamp\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:154:25\n    at execStack (E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\lib\\remote-objects.js:488:7)\n    at RemoteObjects.execHooks (E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\lib\\remote-objects.js:492:10)\n    at phaseAfterInvoke (E:\\51freecode\\FreeCodeCamp\\node_modules\\strong-remoting\\lib\\remote-objects.js:652:10)\n    at runHandler (E:\\51freecode\\FreeCodeCamp\\node_modules\\loopback-phase\\lib\\phase.js:130:5)"
    }
}
```

**Comment by raisedadead** [comment]
@NateLing Can you elaborate how and where you are getting this?
Please share some screen shots, it would be difficult to investigate this without it.

/cc @BerkeleyTrue

**Comment by raisedadead** [comment]
By the looks of it perhaps you are trying to set up FCC locally?

**Comment by NateLing** [comment]
@raisedadead  

```js
(function getFlyer() {
    var flyerKey = '__flyerId__';
    $.ajax({
      url: '/api/flyers/findOne',
      method: 'GET',
      dataType: 'JSON',
      data: { filter: { order: 'id DESC' } }
    })
    // log error
    .fail(function (err) {
      return console.error(err);
    }).done(function (flyer) {
      var lastFlyerId = localStorage.getItem(flyerKey);
      if (!flyer || !flyer.isActive || lastFlyerId === flyer.id) {
        return;
      }
      $('#dismiss-bill').on('click', function () {
        localStorage.setItem(flyerKey, flyer.id);
      });
      $('#bill-content').html(flyer.message);
      $('#bill-board').fadeIn();
    });
```

the error from here

```js
fail(function (err) {
      return console.error(err);
    })
```

**Comment by BerkeleyTrue** [comment]
When there are no flyers in the database the query errors. Hence the error. As you pointed out, the errors are printed to the console. This is by design and not an issue.

Happy Coding!

**Comment by ShrawanLakhe** [comment]
@BerkeleyTrue Hi How does the flyers stored in the datebase? I am facing same issue. Did i need to  manually insert flyers data into the db?

@NateLing Hi, If you have fixed the issue, Can you please elaborate me to fix this issue?
