### ISSUE TITLE
Learnyoumongo on C9 - Connect issues

### ISSUE THREAD

**Issue by Lewis65** [FreeCodeCamp/FreeCodeCamp#8629]
#### Store Data in MongoDB - #2 Connect

https://www.freecodecamp.com/challenges/store-data-in-mongodb

#### Issue Description

Running the commands as directed will not work. After opening a new terminal and attempting to connect, the connection is refused.

#### Browser Information

* Browser Name, Version: Chrome 50.0.2661.102 m on Cloud9

#### Your Code

```js
//mkdir date is already run previously

lewis_:~/workspace $ mongod --port 27017 --dbpath=./data --nojournal
Error parsing command line: unknown option small
try 'mongod --help' for more information

//In new terminal
lewis_:~/workspace $ npm install mongodb
npm WARN package.json chat-example@0.0.0 No repository field.
npm WARN package.json chat-example@0.0.0 No license field.
mongodb@2.1.18 node_modules/mongodb
├── es6-promise@3.0.2
├── readable-stream@1.0.31 (string_decoder@0.10.31, isarray@0.0.1, inherits@2.0.1, core-util-is@1.0.2)
└── mongodb-core@1.3.18 (bson@0.4.23, require_optional@1.0.0)

lewis_:~/workspace $ learnyoumongo verify
✗ Error connecting to mongo. connect ECONNREFUSED 127.0.0.1:27017
```

**Comment by Lewis65** [comment]
Solved issue by including mongod in double quotes ("mongod" --port 27017 --dbpath=./data --nojournal)

**Comment by AntoniosHadji** [comment]
double quotes around the command is a definite error condition, that should not be required and this bug should be reopened.

In addition to the double quote error, I am also getting a failure in installing kerberos when installing learnyoumongo.

**Browser:** Chrome Version 50.0.2661.102 (64-bit) on Ubuntu 14.04
Running on cloud 9

```bash
antonioshadji:~/workspace $ npm install learnyoumongo -g
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> kerberos@0.0.21 install /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyoumongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyoumongo/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:36:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:37:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:446:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:1236:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
/usr/bin/ld: cannot find -lkrb5
/usr/bin/ld: cannot find -lgssapi_krb5
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/kerberos.node] Error 1
make: Leaving directory `/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyoumongo/node_modules/mongodb/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-c9
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v4.4.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyoumongo/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```
