### ISSUE TITLE
Unable to start local instance of FCC

### ISSUE THREAD

**Issue by adityaparab** [FreeCodeCamp/FreeCodeCamp#8759]
Greetings,

I believe I've installed all the dependencies correctly. However, when I `gulp` this error is thrown.
No idea what am I missing out on.

```
C:\My Place\FCC\FreeCodeCamp>gulp
module.js:442
    throw err;
    ^

Error: Cannot find module 'babel-helpers'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\My Place\FCC\FreeCodeCamp\node_modules\babel-core\lib\transformation\file\index.js:34:45)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

C:\My Place\FCC\FreeCodeCamp>
```

Node - v6.2.0
npm - 3.8.9

**Comment by adityaparab** [comment]
Also tried `npm install --save babel-helpers`. No luck.

**Comment by ltegman** [comment]
I'm not able to reproduce this error. Have you tried removing your node_modules folder from the FreeCodeCamp folder and doing a fresh `npm install`?

**Comment by markahuston** [comment]
Go to bed Einstein   I am

**Comment by raisedadead** [comment]
@adityaparab alternatively you can follow the recommended versions of the node and npm as mentioned on the Contributing guidelines and seek any assistance in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors), its way faster to resolve your issue this way.

**Comment by ltegman** [comment]
Closing as stale. As @raisedadead mentioned, using the same version of node/npm we use in production should solve this problem (node 4.X and npm 2). Thanks and happy coding!
