### ISSUE TITLE
cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Zaizai56** [FreeCodeCamp/FreeCodeCamp#9553]
Challenge [Start a Nodejs Server](https://www.freecodecamp.com/challenges/start-a-nodejs-server) has an issue.

I was running the 'make it modular' verify step, when I got this error message:
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188:18)
    at /home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:195:7
    at callback (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:26:15)
    at modFileError (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:31:5)
    at noerr (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:57:12)
    at Exercise.validateModule (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:69:5)
    at Exercise.verifyModuleUsed (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:191:18)
    at Exercise.verify (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:208:20)
    at Exercise.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:40:8)
    at next (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188:19)

User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
This is an issue with the specific [nodeschool workshop](https://github.com/workshopper/learnyounode).

Please report issue's there.

Happy Coding
